### ISSUE TITLE
Duplication of newlines for ModelicaMessage etc. in FMUs

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#1480]
**Reported by beutlich on 13 May 2014 08:15 UTC**
In [FMI#158](https://trac.fmi-standard.org/ticket/158) it is said that ModelicaUtility functions (ModelicaMessage, ModelicaFormatMessage, ModelicaVFormatMessage, ModelicaError, ModelicaFormatError and ModelicaVFormatError) duplicate the newlines if logged as FMU. This is due the case
 * that every ModelicaUtility function (of the MSL) has a trailing newline and
 * the FMU logger adds a trailing newline.

So I wonder why every ModelicaUtility function (of the MSL) is called with a message string that ends with a newline. As jakesson pointed out this is not specified everywhere. Should it be added to the MLS or removed from the MSL?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1480

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 13 May 2014 15:08 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 19 Aug 2014 08:27 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 19 Dec 2014 07:01 UTC**
Ticket retargeted after milestone closed

**Comment by beutlich** [comment]
Clsosing as discussion did not happen.
