### ISSUE TITLE
Modelica.Blocks.Math.LinearDependency has strange formulation

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#1724]
**Reported by Joe Riel on 1 Jun 2015 14:58 UTC**
The relatively new block LinearDependency seems strange. It's defining equation is `y = y0*(1 + k1*u1 + k2*u2);`. y0 is a parameter; its description says it is an initial value, which makes no sense.  It is a scale factor (with a useless default of 0).  However, if its value is nonzero, then one cannot produce an output with a non-zero offset.  I'm thinking the block would be slightly more useful if the defining equation were `y = y0 + k1*u1 + k2*u2`.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1724

**Comment by modelica-trac-importer** [comment]
**Comment by Joe Riel on 1 Jun 2015 15:32 UTC**
A correction.  A nonzero value of y0, which is practically necessary to have a useful block, means the offset must be nonzero.   With the proposed change, the offset is independent of the gains.

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 1 Jun 2015 20:14 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 18 Aug 2015 12:08 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 31 Aug 2015 09:29 UTC**
There is only one component of LinearDependency in the MSL, however the Real output Modelica.Blocks.Examples.RealNetwork1.linearDependency1.y is not used in the example model.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 28 Sep 2015 11:45 UTC**
The proposal would lead to a non-backwards compatible change of the library (which is not possible with MSL 3.2.1 build 4). Therefore, the milestone is moved to 3.2.2.

To avoid a non-backwards compatible change in 3.2.2, I would suggest to just improve the documentation of this block (and the use case for which it was designed).

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 11 Dec 2015 14:20 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by ahaumer on 18 Dec 2015 12:05 UTC**
IMHO the implementation is erroneous and will be changed when a conversion script is applicable. This is stated in the documenation of the block.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 20 Dec 2015 20:45 UTC**
I reverted the changes from 811c96eb7a71c641c5896f9b27bbf34016f1d097 of Math.mo with 8bd005ca83368db93f4b1ed5737c0d82fd24d6d4 since

 * it is not clear if this change went in by design or by side-effect (no commit message was given)
 * the comment used the undesired h3 headline
 * the formula in the comment was invalid.

Please revise again for MSL 3.2.2. For that reason I changed the milestone back to MSL 3.2.2 which should be reset again once the comment is without errors. Sorry for the extra work.

**Comment by modelica-trac-importer** [comment]
**Comment by ahaumer on 23 Dec 2015 18:28 UTC**
Please, do not revert - give a comment what's wrong in your opinion.

Once again: IMHO the implementation is wrong and will be corrected in the next major version (conversion script needed; ticket remains open). This is stated in the documentation (92389bffefad8506bd3854bebf16a843f89cf2df).

**Comment by beutlich** [comment]
Point to @JoeRiel.

**Comment by beutlich** [comment]
My proposal #2886 was rejected by @MartinOtter .

@AHaumer @MartinOtter Please provide an alternative fix!

**Comment by JoeRiel** [comment]
On Fri, 09 Aug 2019 06:36:14 -0700
Thomas Beutlich <notifications@github.com> wrote:

> My proposal #2886 was rejected by @MartinOtter .
> 
> @AHaumer @MartinOtter Please provide an alternative fix!
> 

Hmm.  The original is definitely wrong and completely non intuitive.  
I understand the reluctance to change a model, as doing so will definitely
change any models that use it, but suspect it was never/rarely used
given its weirdness.   Maybe name the fixed model LinearDependent, or
TwoInputLinear, or something like that.

-- 
Joe Riel

**Comment by beutlich** [comment]
#3088 is my second attempt to fix this issue.
