### ISSUE TITLE
Noise: Improve automatic local seed function

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#1861]
**Reported by beutlich on 16 Dec 2015 21:03 UTC**
This simply is a reminder for the following note in Noise.mo

https://github.com/modelica/ModelicaStandardLibrary/blob/bf7185414962b490700c96c160632c625ef52e4f/Modelica/Blocks/Noise.mo#L596-L599

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1861

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 13 Oct 2016 20:46 UTC**
Can this be closed as obsolete after resolving #1957 for MSL 3.2.2?

**Comment by beutlich** [comment]
@MartinOtter Is this still planned?

**Comment by MartinOtter** [comment]
I would suggest to first have tools with MSL 3.2.3 support and only then improve this

**Comment by dietmarw** [comment]
@MartinOtter I guess you mean MLS 3.3 support, correct?

**Comment by MartinOtter** [comment]
> 
> 
> @MartinOtter I guess you mean MLS 3.3 support, correct?

Yes (sorry).
