### ISSUE TITLE
Change greek parameter name 'mue' to 'mu', 'nue' to 'nu' and 'lamda' to 'lambda' in MSL

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#194]
**Reported by christiankral on 23 Jul 2009 15:07 UTC**
In the MSL the following packages are using a parameter called `mue`:

 * `Modelica.Mechanics.MultiBody`
 * `Modelica.Mechanics.Rotational` 
 * `Modelica.Mechanics.Translational`
 * `Modelica.Constants`

The intention was to represent the Greek letter for m (µ), but it is unfortunately spelled incorrectly. The correct spelling is "mu", not "mue". Therefore, these parameter names should be changed once the next conversion script is scheduled.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/194

**Comment by modelica-trac-importer** [comment]
**Comment by thorade on 14 Aug 2009 07:42 UTC**
In Modelica.Thermal.FluidHeatFlow.Media there is in all four media a variable "lamda" which I think should be "lambda"

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 14 Aug 2009 07:57 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 21 May 2010 11:10 UTC**
Milestone MSL3.3 deleted

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by beutlich** [comment]
> Comment by thorade on 14 Aug 2009 07:42 UTC
In Modelica.Thermal.FluidHeatFlow.Media there is in all four media a variable "lamda" which I think should be "lambda"

@thorade This is covered by #2170.

**Comment by beutlich** [comment]
Also nue should be renamed to nu then. Will also update #2170 for the conversion.
