### ISSUE TITLE
Move partial transformer to interfaces

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#199]
**Reported by AHaumer on 26 Aug 2009 06:12 UTC**
Whenever a conversion script is allowed, move partial BasicTransformer from Modelica.Electrical.Machines.Components to Modelica.Electrical.Machines.Interfaces.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/199

**Comment by modelica-trac-importer** [comment]
**Modified by AHaumer on 26 Mar 2010 07:51 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 2 Mar 2012 09:04 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 20 Dec 2016 16:40 UTC**

**Comment by modelica-trac-importer** [comment]
**Changelog removed by ahaumer on 20 Dec 2016 16:40 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 20 Dec 2016 16:40 UTC**

**Comment by AHaumer** [comment]
Seems to be already done - I can't remember who, I can't remember when. 
If nobody contraditcs, we should close this ticket.

**Comment by beutlich** [comment]
Resolved by #2929.
