### ISSUE TITLE
Incorrect homotopy in Modelica.Fluid.Machines.BaseClasses.PartialPump

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#1995]
**Reported by hansolsson on 10 May 2016 08:00 UTC**
The equation (actually two of them):
```
head = homotopy((N/N_nominal)^2*flowCharacteristic(V_flow_single* N_nominal/N), 
N/N_nominal*(flowCharacteristic(0)+delta_head_init*V_flow_single));
```
is not unit-correct; in the simplified version delta_head_init\*V_flow_single has the correct unit m<sup>4</sup>/s but flowCharacteristic(0) has unit m.

I assume the idea was to use a linearization such as `f(x)=f(0)+(f(x0)-f(0))*x/x0` to compute this - but the `x0` part is missing.

Based on that it should be:
```
head = homotopy((N/N_nominal)^2*flowCharacteristic(V_flow_single* N_nominal/N), 
N/N_nominal*(flowCharacteristic(0)*(N/N_nominal)+delta_head_init*V_flow_single/V_flow_single_init));
```
Which is unit-correct, but so is the simpler variant:
```
head = homotopy((N/N_nominal)^2*flowCharacteristic(V_flow_single* N_nominal/N), 
N/N_nominal*(flowCharacteristic(0)+delta_head_init*V_flow_single/V_flow_single_init));
```
However, in practice both would cause errors since V_flow_single_init is as default 0 - which would lead to division by zero (actually zero divided by zero since delta_head_init is also zero in those cases).

Thus the actual corrections is more complex.

Note that as long as the homotopy-solver isn't activated this will not cause any problems.

The issues has been present at least since MSL 3.2.1; maybe earlier. It isn't detected by Dymola 2016 FD01 and earlier due to an unrelated issue.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1995

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 10 May 2016 08:23 UTC**
Something that was indirectly stated before (but should be emphasized is that): as long as system.m_flow_start is zero (the default) the unit-incorrect part adds zero and can thus be ignored.

Correction: The first sentence of the ticket should say: 

The equation (actually two of them):
```
head = homotopy((N/N_nominal)^2*flowCharacteristic(V_flow_single* N_nominal/N), 
N/N_nominal*(flowCharacteristic(0)+delta_head_init*V_flow_single));
```
is not unit-correct; in the simplified version delta_head_init\*V_flow_single has the **in**correct unit m<sup>4</sup>/s but flowCharacteristic(0) has the **correct** unit m.

**Comment by modelica-trac-importer** [comment]
**Modified by fcasella on 11 Nov 2016 15:33 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by fcasella on 11 Nov 2016 15:34 UTC**

**Comment by HansOlsson** [comment]
It seems this one is only partially corrected and ModelicaTest.Fluid.TestComponents.Machines.TestControlledPump  thus fails with division by zero.
