### ISSUE TITLE
Names of CubicInterpolation_DP() und CubicInterpolation_MFLOW() are misleading

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#2006]
**Reported by wischhusen on 6 Jun 2016 07:42 UTC**
Modelica.Fluid.Dissipation.Utilities.Functions.General.CubicInterpolation_DP() calculates a Reynolds number from other Re-inputs but does not take a pressure difference as input
Modelica.Fluid.Dissipation.Utilities.Functions.General.CubicInterpolation_MFLOW() calculates a lambda but does not take a mass flow as input

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2006

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 14 Sep 2016 19:05 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 14 Sep 2016 19:06 UTC**

**Comment by wischhusen** [comment]
How to auto-convert models that have function calls where the name or path of the function has changed? It seems that convertClass() should somehow have the functionality. But it does not work in my tool.

`equation
Re=Modelica.Fluid.Dissipation.Utilities.Functions.General.CubicInterpolation_MFLOW(1, 2, 3, 4, 5);`

If we change the name of the function how can we convert the call in user libraries?

**Comment by beutlich** [comment]
> If we change the name of the function how can we convert the call in user libraries?

@HansOlsson Is it generally possible?

**Comment by HansOlsson** [comment]
>>If we change the name of the function how can we convert the call in user libraries?
> @HansOlsson Is it generally possible?

Yes, convertClass should convert function calls as well (the specification just discusses converting classes so it should be covered, and Dymola has implemented it). I don't know if there is a specific issue in this case.

**Comment by wischhusen** [comment]
We can give it a try.
