### ISSUE TITLE
Missing obsolete annotation

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#2100]
**Reported by hansolsson on 8 Nov 2016 13:45 UTC**
Modelica 3.2 revision 2 added (see #877):
  annotation(obsolete = "message");

The intention is to explain why a particular class is obsolete, and thus this cannot be in the base-class Modelica.Icons.ObsoleteModel

However, it should be classes extending from it - with appropriate message - but that seems to be lacking from all models using it:

* [x] Modelica.Electrical.Spice3.Internal.BJT (and sub-classes)
* [x] Modelica.Electrical.Spice3.Internal.Bjt3.*
* [x] Modelica.Electrical.Spice3.Internal.Bjt.Bjt3Variables
* [x] Modelica.Electrical.Spice3.Internal.Bjt.BjtModelLineVariables
* [x] Modelica.Electrical.Spice3.Internal.Bjt.BjtVariables
* [x] Modelica.SIunits.Conversions.ConversionIcon
* [x] Modelica.Electrical.Spice3.Internal.Mos2.drainCur
* [x] Modelica.Electrical.Spice3.Internal.SpiceRoot.initJunctionVoltages
* [x] Modelica.Electrical.Spice3.Internal.Functions.junction2SPICE3MOSFET
* [x] Modelica.Electrical.Spice3.Internal.Functions.junctionCap
* [x] Modelica.Electrical.Spice3.Internal.SpiceRoot.limitJunctionVoltage
* [x] Modelica.Electrical.Spice3.Internal.ModelcardBJT
* [x] Modelica.Electrical.Spice3.Internal.Mos.mos2CalcCalcTempDependencies
* [x] Modelica.Electrical.Spice3.Internal.Mos.mos2CalcInitEquations
* [x] Modelica.Electrical.Spice3.Internal.Mos.mos2CalcNoBypassCode
* [x] Modelica.Electrical.Spice3.Internal.Mos2.mos2ModelLineParamsInitEquations
* [x] Modelica.Electrical.Spice3.Internal.Mos2.mos2RenameParameters
* [x] Modelica.Mechanics.Rotational.Interfaces.PartialElementaryOneFlangeAndSupport
* [x] Modelica.Mechanics.Translational.Interfaces.PartialElementaryOneFlangeAndSupport
* [x] Modelica.Mechanics.Rotational.Interfaces.PartialElementaryTwoFlangesAndSupport
* [x] Modelica.Mechanics.Translational.Interfaces.PartialElementaryTwoFlangesAndSupport
* [x] Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SaliencyCageWinding_obsolete
* [x] Modelica.Magnetic.FundamentalWave.BasicMachines.Components.SymmetricMultiPhaseCageWinding_obsolete
* [x] Modelica.Math.tempInterpol1
* [x] Modelica.Math.tempInterpol2
* [x] Modelica.Mechanics.MultiBody.Sensors.TansformAbsoluteVector
* [x] Modelica.Mechanics.MultiBody.Sensors.TansformRelativeVector
* [x] Modelica.Icons.TypeComplex
* [x] Modelica.SIunits.LoundnessLevel
* [x] Modelica.SIunits.Loundness
* [x] Modelica.Blocks.Interfaces.Adaptors.*
* [x] Modelica.Icons.Library
* [x] Modelica.Icons.Library2
* [x] Modelica.Icons.GearIcon
* [x] Modelica.Icons.MotorIcon
* [x] Modelica.Icons.Info
* [x] Modelica.Blocks.Interfaces.BlockIcon
* [x] Modelica.Blocks.Interfaces.BooleanBlockIcon
* [x] Modelica.Blocks.Interfaces.DiscreteBlockIcon
* [x] Modelica.Blocks.Interfaces.IntegerBlockIcon
* [x] Modelica.Blocks.Interfaces.partialBooleanBlockIcon
* [x] Modelica.Electrical.Digital.Converters.LogicToXO1
* [x] Modelica.Electrical.Digital.Converters.LogicToXO1Z
* [x] Modelica.Fluid.Icons.VariantLibrary
* [x] Modelica.Fluid.Icons.BaseClassLibrary
* [x] Modelica.Math.baseIcon1
* [x] Modelica.Math.baseIcon2

Most of them already explain this, but some in text, some in description etc. Using the annotation just ensures consistency.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2100

**Comment by christiankral** [comment]
Added obsolete annotation for maint/3.2.2 in b185b43 and master in 830e52b.

**Comment by beutlich** [comment]
Also:
```
Modelica.Mechanics.MultiBody.Sensors.TansformAbsoluteVector
Modelica.Mechanics.MultiBody.Sensors.TansformRelativeVector
Modelica.Icons.TypeComplex
Modelica.SIunits.LoundnessLevel
Modelica.SIunits.Loundness
Modelica.Blocks.Interfaces.Adaptors.*
```

**Comment by beutlich** [comment]
Also:
```
Modelica.Icons.Library
Modelica.Icons.Library2
Modelica.Icons.GearIcon
Modelica.Icons.MotorIcon
Modelica.Icons.Info
Modelica.Blocks.Interfaces.BlockIcon
Modelica.Blocks.Interfaces.BooleanBlockIcon
Modelica.Blocks.Interfaces.DiscreteBlockIcon
Modelica.Blocks.Interfaces.IntegerBlockIcon
Modelica.Blocks.Interfaces.partialBooleanBlockIcon
Modelica.Electrical.Digital.Converters.LogicToXO1
Modelica.Electrical.Digital.Converters.LogicToXO1Z
Modelica.Fluid.Icons.VariantLibrary
Modelica.Fluid.Icons.BaseClassLibrary
Modelica.Math.baseIcon1
Modelica.Math.baseIcon2
```
