### ISSUE TITLE
Replace Modelica.StateGraph.Temporary.anyTrue/allTrue by Modelica.Math.BooleanVectors.anyTrue/andTrue

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#2112]
**Reported by beutlich on 14 Nov 2016 10:38 UTC**
Should Modelica.StateGraph.Temporary.anyTrue/allTrue be removed and substituted by Modelica.Math.BooleanVectors.anyTrue/andTrue?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2112

**Comment by MartinOtter** [comment]
This is just cosmetics and no bug. Removed the bug-label.
