### ISSUE TITLE
What is the usage recommendation for class?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#2128]
Since 09e4eae1eac8e3a7db30b3ca4e55066abaf55682, in ModelicaReference.Classes.'class' the usage recommendation of "class" is given by

>    "class" should only be used to define ExternalObject

However, "class" is frequently used troughout MSL, ModelicaServices and ModelicaReference as non-specialized class with annotation DocumentationClass=true.

The DocumentationClass annotation was controversially discussed and introduced in #1062 (back in 2013 for MLS 3.2r2), but as 09e4eae1eac8e3a7db30b3ca4e55066abaf55682 originates from 2010, I believe it was overlooked to adapt the class recommendation for ModelicaReference.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2128

**Comment by akloeckner** [comment]
This is related to: https://github.com/modelica/ModelicaStandardLibrary/issues/1860

**Comment by HansOlsson** [comment]
Ok, I understand it now: unless/until we have a specialized documentation-class then "class" seems like the preferred option for a documentation-class, and the ModelicaReference should indicate that.
