### ISSUE TITLE
ComplexBlocks.Sources.LogFrequencySweep is not complex

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#2157]
Why is the LogFrequencySweep in the ComplexBlocks package?  Its output is real. Shouldn't it be in Blocks.Sources?

**Comment by tbeu** [comment]
This requires a conversion script.

**Comment by beutlich** [comment]
This requires a conversion script.

See #1850 for the corresponding ticket that added this block.

**Comment by AHaumer** [comment]
The block is mainly used in the ComplexBlock - Examples.

**Comment by AHaumer** [comment]
It should go rather to a Utilities package of ComplexBlocks ...

**Comment by AHaumer** [comment]
As far as I remmebr, the block can't be moved now due to backwards compatibility,

**Comment by beutlich** [comment]
> As far as I remmebr, the block can't be moved now due to backwards compatibility,

Exactly. The milestone is set to MSL_next-MAJOR-version for that reason.

**Comment by christiankral** [comment]
I will move `ComplexBlocks.Sources.LogFrequencySweep` to `Blocks.Source`, as it is a signal source: this is where it belongs to.

**Comment by beutlich** [comment]
Havea look at https://github.com/modelica/ModelicaStandardLibrary/pull/2158/files. Might save you some typing.
