### ISSUE TITLE
Changing constants (2018 edition)!

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#2207]
This seems similar to #1813 - but is different since it is the **final** change for many of the constants.
This means that e.g. elementary charge and Avogrado's constant (similarly as the speed of light) will be defined to have specific values - instead of being measured.

The branch HansOlsson:HansOlsson-codata2017 contain the best available data so far based on http://www.bipm.org/utils/common/pdf/si-brochure-draft-2016b.pdf

Road-map for the change is: http://www.bipm.org/utils/common/pdf/SI-roadmap.pdf#page=3
The values are not yet accepted, so the change cannot be merged yet.

**Comment by thorade** [comment]
Also related: #1241 and #1266

**Comment by beutlich** [comment]
The 9th edition of the SI brochure is available at https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf

**Comment by thorade** [comment]
Related: https://github.com/usnistgov/REFPROP-issues/issues/239
