### ISSUE TITLE
Update contributor's affiliations

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2287]
The affiliated email of Christoph Clauss at Fraunhofer is no longer valid and needs to be updated in Electrical.Analog, Electrical.Digital and Electrical.Spice3.

**Comment by beutlich** [comment]
The list of ontributors in Modelica.UsersGuide.Contact also needs to be updated.

**Comment by kristinmajetta** [comment]
The affiliated email of Christoph Clauß was changed in Modelica.Electrical.Analog
SHA-1: f0c83633b597955c96220ba0f3ded1c17ea9a283

**Comment by kristinmajetta** [comment]
The affiliated email of Christoph Clauß was changed in Modelica.Electrical.Digital and Modelica.Electrical.Spice3
SHA-1: af648f9e83b2dba953fd626a984f75601d16cab4
