### ISSUE TITLE
MyComplex vs. Complex

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2304]
Left over from #1122: 
> But why not use Complex directly like the other packages already do?

Utilize the record Complex (and defined operators) instead of defining own record Modelica.Media.Air.ReferenceMoistAir.Utilities.Ice09_Utilities.Basic.MyComplex and functions MyComplexF.* to avoid redundancy.

Note, that there is Modelica.Media.Air.ReferenceMoistAir.Utilities.Ice09_Utilities.Basic.MyComplexF.'log' but no equivalent function in operator record Complex.

**Comment by svanman1970** [comment]
hacktoberfest

**Comment by AHaumer** [comment]
Why do you direct this question to Martin and me?
Why don't ask the library officers of Modelica.Media?

**Comment by casella** [comment]
Conceptually, this is a trivial fix, but in practice it is quite tedious and it is easy to mess up. Furthermore, I don't see any test model in the MSL to check if the results are the same.

@wischhusen would you be available to take care of this issue (possibly also for the next minor release)?

**Comment by beutlich** [comment]
> @wischhusen would you be available to take care of this issue (possibly also for the next minor release)?

@wischhusen Please let me know if you can manage for MSL 4.0.0?

**Comment by beutlich** [comment]
> @wischhusen Please let me know if you can manage for MSL 4.0.0?

I prepared #3131 for it.
