### ISSUE TITLE
Unused parameters in Modelica.Electrical.Analog.Semiconductors.SimpleTriac

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2349]
The parameters IDRM, VTM, IH, ITM, VGT, IGT, TON, TOFF, Vt, Nbv in Modelica.Electrical.Analog.Semiconductors.SimpleTriac are declared but never referenced.

**Comment by kristinmajetta** [comment]
parameters IDRM, VTM, IH, ITM, VGT, IGT, TON, TOFF, Vt, Nbv used in Modelica.Electrical.Analog.Semiconductors.SimpleTriac 
SHA-1: b7bbecb9203ab3b370096d0bf5521fbaf4e5c618
