### ISSUE TITLE
Typo in Modelica.Electrical.Analog.Ideal.IdealizedOpAmpLimted

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2361]
Split issue from #2270: A minor issue is that the class name Modelica.Electrical.Analog.Ideal.IdealizedOpAmpLimted has a typo; **Limted** should be **Limited**. 

@JoeRiel FYI

**Comment by kristinmajetta** [comment]
Changing the class name would be a non-backwards compatible change. We need to wait for the next MSL-version where those changes are allowd
