### ISSUE TITLE
Modelica.Fluid.Examples.AST_BatchPlant: Medium model to water/ sodium chloride missing

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [modelica/ModelicaStandardLibrary#2374]
Dear Modelica.Fluid developers,

I recently have been looking in the very interesting and well documented example Modelica.Fluid.Examples.AST_BatchPlant contained within Modelice 3.2.2

The model nicely shows how to model a batch plant from process engineering domain. However the model uses Modelica.Media.Water.StandardWater to model the media contained withing the vessels.

In the description, however, it is mentioned that the model describes a process which evaporates water from a water sodium chloride mixture.  The Media model

> Modelica.Media.Electrolytes.WaterNaCl

which is uncommented in the model is missing in Modelica.Media.

I was wondering if Modelica.Media.Electrolytes.WaterNaCl has been included in an earlier version of Modelica and might be added again. Thanks!

**Comment by casella** [comment]
I am not aware such medium model was ever part of Modelica.Media. Maybe that was a reference to a local modified version of Modelica.Media that never went into the official repository and was consequently commented out from the plant model code. I removed that reference in #2559 to avoid confusion in the future.

Of course it would be possible to locally define a medium model with the properties of that solution (e.g. by extending from Modelica.Media.Water.ConstantPropertyLiquidWater, and then use it. Feel free to open a PR if you want to implement that.
