### ISSUE TITLE
Incorrect assert statement in IF97_Utilities.BaseIF97

### ISSUE THREAD

**Issue by greenwoodms06** [modelica/ModelicaStandardLibrary#2385]
Assert statement checks if T >= 273.16 and then uses `triple.ptriple` which appears to be incorrect.

line ~3020 (Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.psat)
```
assert(T >= 273.16, "IF97 medium function psat: input temperature (= "
     + String(triple.ptriple) + " K).\n" +
    "lower than the triple point temperature 273.16 K");
```

Potential Actions:
- change `String(triple.ptriple)` to `String(T)`
or
- change `String(triple.ptriple)`  to `String(triple.Ttriple)` and rephrase warning

**Comment by HansOlsson** [comment]
Good catch, but wrong solution I think.

I believe you refer to Modelica.Media.Water.IF97_Utilities.BaseIF97.Basic.psat with:
```
assert(T >= 273.16, "IF97 medium function psat: input temperature (= "
     + String(triple.ptriple) + " K).\n" +
    "lower than the triple point temperature 273.16 K");
```

That should be `T` - shouldn't it? But possibly change 273.16 to `triple.Ttriple`.

**Comment by greenwoodms06** [comment]
@HansOlsson Yes that is the line. Based on the current phrasing yes I think you are correct. I updated the original post to reflect your comment.
