### ISSUE TITLE
Zener Diode Symbol incorrect

### ISSUE THREAD

**Issue by ceraolo** [modelica/ModelicaStandardLibrary#2402]
Consider Modelica.Electrical.Analog.Semiconductors.ZDiode.
Its symbol is identical to the diode symbol (the only difference is that Vt is not displayed).
This makes it difficult to understand diagrams.

In enclose the IEC symbol as taken from an Italian norme compliant with IEC 60617-2004 (the dots are not part of the symbol; the grey should be black).
Unfortunately by now I have not access to more recent standards.
![zener1](https://user-images.githubusercontent.com/7373030/33787322-fedf7a38-dc6c-11e7-93ce-4d44ed007641.png)

**Comment by kristinmajetta** [comment]
symbol changed in SHA-1: dcd91982e3e5125b7d99c3163fd6cba3855c705a
