### ISSUE TITLE
Remove Comparison Signal from regression Test 

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#2405]
**Reported by @FrenkelJ on 2017-12-14T17:25:40+01:00**

As already mentioned in #1741 the Model

Modelica.Mechanics.MultiBody.Examples.Systems.RobotR3.fullRobot

uses the Signals `axis*.gear.bearingFriction.startBackward` and `axis*.gear.bearingFriction.startForward` for each axis for comparison.

Because these values depent very sensitiv on solver adjustment I propose to remove them from the comparison signals.

For Example take a look at axis1 and axis2 calculated with Dymola.

Stop time = 1e-3 = 0.001
Debug: Event logging

**Tolerance = 0.0001 (default value):**
`axis2.gear.bearingFriction.startBackward` switched at `0.0006288609713011297 s` on and off - in the result view diagram no top is visible
`axis1.gear.bearingFriction.startBackward` become at `0.0007486864492256363 s` true and at `0.0007486947222974626 s` again false - top in result view diagram

**Tolerance = 0.00001 = 1e-05:**
`axis2.gear.bearingFriction.startBackward` become at `0.0006288330859710835 s` true and at `0.0006288459308383774 s` again false - top in result view diagram
`axis1.gear.bearingFriction.startBackward` become at `0.000748620647738925 s` true and at `0.0007486367092876979 s` again false - top in result view diagram

**Tolerance = 1e-06:**
`axis2.gear.bearingFriction.startBackward` switched at `0.0006288298242823198 s` on and off - in the result view diagram no top is visible
`axis1.gear.bearingFriction.startBackward` become at  `0.0007486127956879836 s` true and at `0.0007486292503238141 s` again false - top in result view diagram

**With Tolerance 1e-06 and Stop time = 2 s**
both tops not visible.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2219

**Comment by GallLeo** [comment]
Removed requested signals from list of comparison signals. Ticket can be closed after upload of new reference results.
