### ISSUE TITLE
CombiTable2D tests with unknown variables in reference results

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaStandardLibrary#2407]
The following tests in RegressionTesting/ReferenceResults/MSL/trunk/ModelicaTest/Tables/CombiTable2D have unknown `surface.y[…]` variables in the reference results:
- Test15
- Test16
- Test17

A suppose these come from a vendor specific implementation of ModelicaServices, and I guess the lists of comparison variables for these tests should simply be empty.

**Comment by sjoelund** [comment]
Only variables that are part of `Modelica.Utilities.Internal.PartialModelicaServices.Animation.PartialSurface` should be present, right?

**Comment by beutlich** [comment]
Yes, but these variables are of no use for the regression here.

**Comment by sjoelund** [comment]
Those are the only variables though...

**Comment by GallLeo** [comment]
I now emptied the list of comparison signals. As there are no public variables, I don't think result comparison does make a lot of sense for these test cases.

Ticket can be closed after upload of new reference results.
