### ISSUE TITLE
Use ground plane visualizer directly in the World

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2432]
Since `Modelica.Mechanics.MultiBody.Visualizers.Ground` has relation to `Modelica.Mechanics.MultiBody.World`, it could be a part of it. The following questions arise:
1. Should be the ground plane origin always fixed to the World origin?
2. Should be the orientation of the plane coupled to the gravity normal vector?

**Comment by beutlich** [comment]
Reset milestone since 66345025f76bdfbb06ac7cd33e53707a25402718 went to master branch.

**Comment by HansOlsson** [comment]
This change causes regressions in a commercial library (FlightDynamics); and in theory there could be other similar cases.

Basically if a library made their own world-object (by copying World from MSL and adding parts) and used it as "inner MyWorld world;" the "outer World world;" in MSL no longer matches the inner component.

I don't see that we have stated that making your own inner-objects is not fully supported.

**Comment by HansOlsson** [comment]
Oh, perhaps better to open new issue. Will do that.
