### ISSUE TITLE
Superfluous parameter 'height' in MultiBody.Visualizers.Ground

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2434]
Since `Modelica.Mechanics.MultiBody.Visualizers.Ground` uses a surface visualizer instead of a box, the parameter `height` became superfluous. See also discussion #1843.

**Comment by MartinOtter** [comment]
Removed bug label, because a superflous parameter is no bug

**Comment by beutlich** [comment]
Parameter height is used to display the height of the box.
