### ISSUE TITLE
Same name R used for universal and specific gas constant

### ISSUE THREAD

**Issue by hubertus65** [modelica/ModelicaStandardLibrary#2438]
The same name for the universal and specific gas constant can lead to errors, as we had in #2377. A name change of either the universal gas constant from R to R_m, or from the specific gas constant R to R_s. Both changes would touch a lot of points and could actually be disruptive for users even with good conversion scripts. Good unit checking would always detect it, good documentation could reduce errors. Therefore I'll pose this issue as discussion.

**Comment by HansOlsson** [comment]
I understand that there are some cases where R is used for the specific gas constant, but I would prefer to keep R for the universal gas constant, since NIST defines it, https://physics.nist.gov/cgi-bin/cuu/Value?r and the ideal gas-law pV=nRT is fairly well-known.

I would also prefer "R_specific" over "R_s".

**Comment by hubertus65** [comment]
Fine with me.

**Comment by beutlich** [comment]
I started to have a closer look at the conversion effort :sweat: and noticed that we already have names like R_gas and R_s for the specific gas constant. Should we rename all such variables to R_specific or just the misleading ones where we currently have R only as ident?

**Comment by beutlich** [comment]
@thorade Do you have any proposals?

**Comment by hubertus65** [comment]
I's say: bite the bullet now and update all places. It could make sense to document such naming conventions at one place per sublibrary and make sure they are followed in commit audits. I have no strong opinion re R_s or R_specific.

**Comment by thorade** [comment]
I agree with Hans and Hubertus to use R for universal gas constant and R_s or R_specific for the gas specific gas constant, so that 
```
R_s = R/MM
```
I would prefer R_s because it is shorter in equations, and is also in line with what I have seen in text-books, but this is not a strong preference either.
