### ISSUE TITLE
Delete obsolete GasForce model from multi-body examples

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2440]
There is an obsolete model `Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.GasForce` which should be removed.
See also #2439.
The model was added in https://github.com/modelica/Modelica/commit/4e06d4b54c357d9797c2ab4a36224908d2e0c951.

**Comment by MartinOtter** [comment]
Removed bug-tag, because having an obsolet model in MSL is no bug.
