### ISSUE TITLE
False color of blocks in Modelica.ComplexBlocks

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2477]
Regarding the color of the interfaces defined in `Modelica.ComplexBlocks.Interfaces`, e.g. ComplexInput, the common color of ComplexBlocks is light blue, in RGB: {85,170,255}. The icon style guide Modelica.UsersGuide.Conventions.Icons states that "The main icon color of a component shall be the same for all components of one library." But all blocks of ComplexBlocks use a base class Modelica.Blocks.Icons.Block, i.e. that one with dark blue border.

There should be defined a new particular base class for ComplexBlocks and used across the library.

**Comment by tobolar** [comment]
Due to similarity to #2486, the milestone should be the same as well.

**Comment by beutlich** [comment]
> Due to similarity to #2486, the milestone should be the same as well.

#2486 is fixed for MSL 3.2.3.

**Comment by beutlich** [comment]
@tobolar Can you prepare a PR on this one? Thanks.

**Comment by tobolar** [comment]
Will go for it.
