### ISSUE TITLE
Add unit and displayUnit to signal input and output representing an angle

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#2488]
There are a couple models in the MSL which provide an angle signal input or output. However, when simulating and displaying such angles, the displayUnit can often NOT be switched to "deg", since the output is just a RealOutput with no unit. Therefore, the angle signal input and output shall be equipped with ```(unit="rad",displayUnit="deg")```.

This issue applies to the following models (list may not yet be complete):
- Modelica.Blocks.Math.Sin
- ...
- Modelica.Blocks.Math.Atan2
- Modelica.Blocks.Math.WrapAngle
- Modelica.Blocks.Math.RectangularToPolar
- Modelica.Blocks.Math.RectangularToPolar
- Modelica.Blocks.Math.Harmonic 
- Modelica.ComplexBlocks.ComplexMath.PolarToComplex
- Modelica.ComplexBlocks.ComplexMath.ComplexToPolar
- Modelica.ComplexBlocks.ComplexMath.Bode
- Modelica.Electrical.Machines.SpacePhasors.Components.Rotator
- Modelica.Electrical.Machines.SpacePhasors.Blocks.Rotator
- Modelica.Electrical.Machines.SpacePhasors.Blocks.ToPolar
- Modelica.Electrical.Machines.SpacePhasors.Blocks.FromPolar
- Modelica.Electrical.Machines.Utilities.ToDQ
- Modelica.Electrical.Machines.Utilities.FromDQ
- Modelica.Magnetic.QuasiStatic.FundamentalWave.Utilities.CurrentController
- Modelica.Electrical.Machines.Utilities.CurrentController
- Modelica.Electrical.Machines.Utilities.VoltageController

**Comment by HansOlsson** [comment]
> There are a couple models in the MSL which provide an angle signal input or output. However, when simulating and displaying such angles, the displayUnit can often NOT be switched to "deg", since the output is just a RealOutput with no unit. Therefore, the angle signal input and output shall be equipped with (unit="rad",displayUnit="deg").

I can understand the need for unit="rad", and I would also hope that we could derive that unit in more cases. However, it may be excessive to use displayUnit="deg" - when looking at polar representation I don't necessarily consider degrees a better choice.

**Comment by AHaumer** [comment]
see #2494 (and #2492), let's continue the discussion on a generalized level in #2494.

**Comment by christiankral** [comment]
OK, to me this sounds like adding the angle unit "rad" is possible without getting the MSL backwards incompatible, right? The displayUnit shall not be included -- so this makes sense to me. I can create a pull request, if we agree to go for adding units to angle inputs and outputs.

**Comment by AHaumer** [comment]
I agree with Hans, displayUnit might be overdone.
It seems that unit (without diplayUnit) won't cause problems or incompatiblities. 
I suggest starting implementation, but I think we won't get all models done for 3.2.3 
Therefore shifting the milestone.

**Comment by AHaumer** [comment]
But don't forget angular velocity ;-)

**Comment by AHaumer** [comment]
I'm just working on the initially mentioned.
For two blocks this isn't possible:
- Modelica.Electrical.Machines.SpacePhasors.Blocks.ToPolar
- Modelica.Electrical.Machines.SpacePhasors.
since the output is a vector of lenght 2, the first element representing the length and the second the angle. Don't know how to set the unit of just 1 element of an arry.

To be sure: We should go through the whole standard library a look for similar occurenes.
Blocks.FromPola

**Comment by AHaumer** [comment]
To be sure: We should go through the whole standard library a look for similar occurenes.

**Comment by AHaumer** [comment]
To be sure: We should go through the whole standard library a look for similar occurenes.
