### ISSUE TITLE
Modelica.Electrical.Analog.Ideal.AD_Converter internal error check fails w/ OpenModelica (v1.11.0 Win64)

### ISSUE THREAD

**Issue by jpaximadis** [modelica/ModelicaStandardLibrary#2493]
Not sure if this is a Modelica standard library issue or an OpenModelica issue, but it was resolved by...

1) Adding:
> import SI = Modelica.SIunits;

2) Changing:

> initial equation
>   for i in 1:N loop
>     y[i] = L.'X';
>   end for;
> 

To:

> initial algorithm
>   for i in 1:N loop
>     y[i] := L.'X';
>   end for;

**Comment by beutlich** [comment]
@sjoelund Is this a tool issue?

**Comment by sjoelund** [comment]
Is this used in any example? The error only seems to trigger for `checkModel` functionality (which is rarely used except for models that are incomplete such as this one).

**Comment by beutlich** [comment]
> Is this used in any example?

Yes, in Modelica.Electrical.Analog.Examples.AD_DA_conversion

**Comment by sjoelund** [comment]
And that model works just fine. So there is only a problem trying to check an incomplete model that has a for-loop such as this one; so it's a minor tool issue.

**Comment by beutlich** [comment]
Well, we can change it as proposed to make OMC happy.
