### ISSUE TITLE
Documentation refers to non existing parameter startTime in Modelica.Blocks.Math.ContinuousMean, Variance and StandardDeviation

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2495]
In the documentation of `Modelica.Blocks.Math.Variance` and `Modelica.Blocks.Math.StandardDeviation` there is stated that "...the computation starts at startTime + t_eps..." but there is no public parameter like startTime. There is only protected `t_0` in the `Variance`block.

**Comment by beutlich** [comment]
Also in ContinuousMean.

**Comment by tobolar** [comment]
If I understand the blocks' code well, what is meant with "startTime" is the `experiment.StartTime` annotation.

**Comment by beutlich** [comment]
Yes, I got the same expression, but wondered why it is spelled different then.
