### ISSUE TITLE
Constant Expressions Bounds

### ISSUE THREAD

**Issue by vruge** [modelica/ModelicaStandardLibrary#2496]
the bounds(min, max) of an constant expression should defined as the the value of the expression.
This is important for the consistent formulation of the inStream operator.
e.g.
`
Real m1 = 0
Real m = m1;
h = posetiveMax(m, eps)  // modelica tools simplified the equation to h=0 and not h=eps
`
which is correct for `m.min <= 0 `

**Comment by sjoelund** [comment]
Isn't this rather a ticket for the Modelica language? https://trac.modelica.org/Modelica/
I also don't see anywhere in the specification that the min/max attribute of m would be used for positiveMax...

**Comment by vruge** [comment]
thanks, I will move it to  https://trac.modelica.org/Modelica/
