### ISSUE TITLE
Dead project link

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2510]
The link in the former [release notes](http://doc.modelica.org/om/Modelica.UsersGuide.ReleaseNotes.Version_3_2_2.html) to [JTI-CS-2011-1-SGO-02-026](https://cordis.europa.eu/project/rcn/101194_en.html/) is dead.

**Comment by ThomasBoedrich** [comment]
Thomas, 
many thanks for fixing the link.

Best regards
Thomas
