### ISSUE TITLE
Broken URI to image in User's Guide

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#2518]
In ```Modelica.UsersGuide.Conventions.Documentation.Format.Figures``` the following figure URI is used:

```
modelica://Modelica/Resources/Images/UsersGuide/Conventions/Images/Blocks/Examples/PID_controller.png
```

The resource, however, does not (any more) exist. The URI shall therefore changed to:

```
modelica://Modelica/Resources/Images/Blocks/PID_controller.png
```

**Comment by dietmarw** [comment]
Christian. No need to open an extra ticket when you already have the fix/solution ready. Simply send the pull request next time. :-)
