### ISSUE TITLE
Missleading documentation in Spice3 package

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaStandardLibrary#2523]
The documentation of [Modelica.Electrical.Spice3](https://doc.modelica.org/om/Modelica.Electrical.Spice3.html) contains this sentence:

> This package should not be used via direct access by a user of the Spice-Library for Modelica.

What is that supposed to mean? Users of the MSL should not use the Spice3 library?
This needs clarifying.

**Comment by kristinmajetta** [comment]
Improved the documentation of Modelica.Electrical.Spice3
SHA-1: 85b9343ece52a13d3edad9a79e1cefc39c3efc60
