### ISSUE TITLE
Threephase PWM algorithm(s) for DC/AC PowerConverters

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#2536]
Electrical.PowerConverters is a really usefull library. 
Unfortunately it lacks multiphase PWM algorithms (similar to Electrical.PowerConverters.DCDC.Control.SignalPWM). 
I know that MULTIphase is a really tricky task, but a threephase PWM is textbook knowledge. 
This would be a great improvement, I'll suggest an implementation.

**Comment by dietmarw** [comment]
You might want to consider to try to use polyphase instead of multi-phase for all newly added components. That saves some work later on when the MSL will be adopt polyphase see also #1865.

**Comment by AHaumer** [comment]
Adding a new drive example using this pwm.
