### ISSUE TITLE
Release notes 3.2.3

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#2565]
We shouldn't forget the release notes ...

**Comment by AHaumer** [comment]
Do you really mean "clean-up" with such a lot of improvements and new models (not big fixes)?

**Comment by AHaumer** [comment]
Dietmar suggested to use my PR #2566 to fill in all contributions to the release notes, and merge them when they're finished.

**Comment by dietmarw** [comment]
This issue can be closed since we have #2566  to deal with the release notes.

**Comment by beutlich** [comment]
> This issue can be closed since we have #2566 to deal with the release notes.

It will be closed automatically once #2566 is merged. Otherwise it is just confusing to tell if this is fixed or not.
