### ISSUE TITLE
Default component name for adaptors

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2569]
Flow to potential adaptors (and potential to flow) have different settings concerning default component name. In particular:
- `GeneralCurrentToVoltageAdaptor` and `GeneralVoltageToCurrentAdaptor` have no defaut names,
- `GeneralAngleToTorqueAdaptor` and `GeneralTorqueToAngleAdaptor` have default names omitting "general" prefix,
- `GeneralPositionToForceAdaptor` and `GeneralForceToPositionAdaptor` have no defaut names,
- `HeatflowToTemperatureAdaptor` and `TemperatureToHeatflowAdaptor` have default names "adaptor".

This should be harmonised. I prefer the version which omits "general" prefix in component name.

**Comment by AHaumer** [comment]
see PR #2570
