### ISSUE TITLE
Add syntax checks for pull requests

### ISSUE THREAD

**Issue by sjoelund** [modelica/ModelicaStandardLibrary#2572]
I think it would be useful to have syntax checking setup to verify that all pull requests are at least a little bit sane. We could do this using some free service like Travis, or I could offer to build using Jenkins on the openmodelica.org servers since a syntax checking job is quite low on resources (the only advantage is pulling docker images faster since we cache them; travis has the advantage of being reasonably available even if it queues for some time and takes a little while to pull docker images it is reasonable if you base them on the same OS).

The things that would change is that there needs to be a file somewhere (`/Jenkinsfile` or `/ travis.yml`) in each branch that should be checked. 

The following is an example that would parse a single library (the old BioChem library in this case) using OpenModelica v1.12.0 and moparser:
[Jenkinsfile.txt](https://github.com/modelica/ModelicaStandardLibrary/files/2061303/Jenkinsfile.txt)
[travis.txt](https://github.com/modelica/ModelicaStandardLibrary/files/2061655/travis.txt) (skipped creating the mos-script for checking; that could either be a separate file or in the travis.yml).

**Comment by beutlich** [comment]
I am all in and enabled https://travis-ci.org/modelica/ModelicaStandardLibrary. Can you send a PR adding the .travis.yml file (note the leading dot). Thanks.

@thorade FYI
