### ISSUE TITLE
Remove obsolete parameter "limitsAtInit"

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaStandardLibrary#2590]
During work on #2561 it was noticed that some blocks still contain the obsolete parameter `limitsAtInit` which can be removed in the next MAJOR version. See also 
153352f08676b88dd9c845fa02157a24a2bc5711 for some additional info on this.

**Comment by beutlich** [comment]
Duplicate of #2226.

**Comment by thorade** [comment]
@beutlich 
https://help.github.com/en/articles/about-duplicate-issues-and-pull-requests
Duplicate of #2226

**Comment by beutlich** [comment]
I did so at 2018-10-26.

**Comment by thorade** [comment]
You marked it manually, and now you also used github special syntax to mark it as duplicate
