### ISSUE TITLE
Version is not updated in ModelicaReference

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#2595]
The version, versionDate, and dateModified annotations were not updated in ModelicaReference for 3.2.3 version:
```
annotation (
  DocumentationClass=true,
  version="3.2.2",
  versionBuild=1,
  versionDate="2016-01-15",
  dateModified = "2016-01-15 08:44:41Z",
```
They should be updated to 3.2.3 and the dates changed as well.

**Comment by dietmarw** [comment]
@eshmoylova Thanks for catching this. Once you accepted the member invitation I'd like to ask you to review #2597 and approve it.
