### ISSUE TITLE
Variable used in a dimension in Modelica.Electrical.MultiPhase.Functions.symmetricOrientationMatrix

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#2596]
The function Modelica.Electrical.MultiPhase.Functions.symmetricOrientationMatrix has new protected variables **nBase** and **oBase**, introduced in 3.2.3:
https://github.com/modelica/ModelicaStandardLibrary/blob/eea74432d6006527b41676547ec2326d8bcbb8f2/Modelica/Electrical/MultiPhase.mo#L2693
https://github.com/modelica/ModelicaStandardLibrary/blob/eea74432d6006527b41676547ec2326d8bcbb8f2/Modelica/Electrical/MultiPhase.mo#L2696

**nBase** is used as a dimension of **oBase**, but it is a variable. According to the Specification 3.4, Section 12.2:
>The dimension sizes not declared with (:) of each array result or array local variable [i.e., a non-input components] of a function must be either given by the input formal parameters, or given by constant or parameter expressions, or by expressions containing combinations of those (Section 12.4.4).

It would be better to declare **nBase** as a parameter, but it would not be correct either. The modification of **nBase** contains the input **m**. Inputs have discrete-time variability in functions (if I remember correctly), so we cannot use them in a modification of a parameter.

It is a regression comparing to 3.2.2.

**Comment by beutlich** [comment]
See a7f7cffe2dec9d3bacb0a9c8da8afa19819d4fc7 for #1997.

**Comment by HansOlsson** [comment]
As far as I recall "input formal parameters" just means "inputs" to functions; see 12.1.1 - i.e. it is a "parameter" when calling the function - but not a "parameter" in Modelica. I believe that is an influence from computer science and other languages, and I agree that it is problematic.

So, `m `is an input and therefore "input formal parameter", but `nBase `isn't; using 
`Modelica.SIunits.Angle oBase[numberOfSymmetricBaseSystems(m)]=o[1:mBase:m];`

**Comment by eshmoylova** [comment]
I second @HansOlsson's suggestion. It would solve the issue.

**Comment by beutlich** [comment]
What about `Modelica.SIunits.Angle oBase[:]=o[1:mBase:m];`?

**Comment by HansOlsson** [comment]
> What about Modelica.SIunits.Angle oBase[:]=o[1:mBase:m];?

I think that is less good, since the size will depend on mBase - which has similar issue as nBase.
