### ISSUE TITLE
Examples using obsolete ground visualization

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#2601]
Several examples of this:

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheel:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetDriving:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.RollingWheelSetPulling:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

Checking model Modelica.Mechanics.MultiBody.Examples.Elementary.Surfaces:
Warning: Component type specifier Ground specified an obsolete type: Obsolete model - use ground visualization feature in Modelica.Mechanics.MultiBody.World, or use model Modelica.Mechanics.MultiBody.Visualizers.Rectangle instead.

**Comment by tobolar** [comment]
My impression was that examples should stay untouched for backward compatibility. Is there some general recommendation for such cases?

**Comment by HansOlsson** [comment]
If you look at the examples it doesn't look nice to have some components marked as being obsolete, with an icon clearly indicating that something is wrong.

If a user duplicates the examples to change it they will also get the warning for using obsolete models.

The downside with changing it is that a user-model extending the Example-model will no longer work. I hope people don't do that too often - and I think we have made other changes that may break that, but I am not 100% sure.

**Comment by beutlich** [comment]
I guess we need to set these examples as obsolete and add new examples not containing the Ground class.

**Comment by tobolar** [comment]
> I hope people don't do that too often

Hope so as well.

>  set these examples as obsolete and add new examples
@HansOlsson Do you agree? Is some effort but I could do it shortly.

**Comment by HansOlsson** [comment]
> @HansOlsson Do you agree? Is some effort but I could do it shortly.

I can accept it, but would have preferred the simpler idea of just updating these examples. 
However, if that would be seen as breaking backward compatibility we cannot do that.

**Comment by dietmarw** [comment]
I'm not 100% sure but I think to remember that backward-compatibility was not guaranteed for examples in the past. So users who extend from examples in the MSL were basically on their own and could not expect the models to still work after an upgrade of MSL. Personally I would have nothing against "breaking" example models. Especially since making now copies just adds a lot of unnecessary noise to the library.
