### ISSUE TITLE
Modelica.Mechanics.Rotational.Examples.GenerationOfFMUs

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2604]
Whereas MSL v3.2.2 has nicely drawn connection lines to the springDamper component of Modelica.Mechanics.Rotational.Examples.GenerationOfFMUs

![2018-06-11 11_43_59-generationoffmus - modelica mechanics rotational examples generationoffmus rea](https://user-images.githubusercontent.com/14896695/41224451-cf1392b2-6d6c-11e8-9330-c1c9f8329906.png)

it is no longer the case in v3.2.3-beta.2

![2018-06-11 11_44_10-generationoffmus - modelica mechanics rotational examples generationoffmus - d](https://user-images.githubusercontent.com/14896695/41224456-d33143c6-6d6c-11e8-9b5d-3d4e42a5a061.png)

Is this really the intended behaviour?

**Comment by tobolar** [comment]
Well this comes due to the adaption of icon and of connectors position of AngleToTorqueAdaptor on new GeneralAngleToTorqueAdaptor. Since both adaptors should be compatible to each other I think this is a drawback of it.
Not nice but necessary.

**Comment by beutlich** [comment]
Well, we still can adapt Modelica.Mechanics.Rotational.Examples.Utilities.SpringDamper to match the connector alignment.

But I prefer to have a wider connector distance in the new adaptors since it looks rather sqeezed (while still having vertical space available).

**Comment by tobolar** [comment]
I have no preference.

**Comment by beutlich** [comment]
OK then, I propose to use the same connector alignment as the MultiplexN/DeMultiplexN blocks of Modelica.Blocks.Routing for the old and new adaptors.

**Comment by tobolar** [comment]
1. Do you mean the particular model(s) Multiplex/DeMultiplex or rather MultiplexN/DeMultiplexN with N being 1..6?.
2. And do you really mean to apply it for both the old and new adaptors?

**Comment by beutlich** [comment]
I will work on a PR and let you review it.

**Comment by beutlich** [comment]
After spending too much spare time on old/new adaptors I tend to leave it as is. OK for you?

**Comment by tobolar** [comment]
Fine for me as well.
