### ISSUE TITLE
Broken icon for Modelica.Thermal.FluidHeatFlow.Sources.Ambient

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#2620]
The icon for Modelica.Thermal.FluidHeatFlow.Sources.Ambient changed from 3.2.2 to 3.2.3. In 3.2.2 the text was on top of the circle:
![ambient3 2 2](https://user-images.githubusercontent.com/20460714/41299721-12ad651e-6e32-11e8-9a45-658a76bfc660.png)
In 3.2.3 the text got covered by the circle:
![ambient3 2 3](https://user-images.githubusercontent.com/20460714/41299727-15a44c06-6e32-11e8-93bf-e61397393508.png)

The difference is that in 3.2.2 the circle was inherited from the partial class it extended from and the text added after. In 3.2.3 the class it extends from has changed and it does not contain the circle. The code to draw the circle was added after the code that specifies the text. Starting on line 2540:
https://github.com/modelica/ModelicaStandardLibrary/blob/e69a99ad2abd6ba6a5006d50e896dca97f2dee03/Modelica/Thermal/FluidHeatFlow.mo#L2540
```modelica
</html>"), Icon(coordinateSystem(preserveAspectRatio=true, extent={{-100,-100},{
                100,100}}), graphics={Text(
              extent={{20,80},{80,20}},
              textString="p"), Text(
              extent={{20,-20},{80,-80}},
              textString="T"),         Ellipse(
              extent={{-90,90},{90,-90}},
              lineColor={255,0,0},
              fillColor={0,0,255},
              fillPattern=FillPattern.Solid)}));
```
The suggestion is to change the order in which the circle and the text are written. The above block would be:
```modelica
</html>"), Icon(coordinateSystem(preserveAspectRatio=true, extent={{-100,-100},{
                100,100}}), graphics={Ellipse(
              extent={{-90,90},{90,-90}},
              lineColor={255,0,0},
              fillColor={0,0,255},
              fillPattern=FillPattern.Solid), Text(
              extent={{20,80},{80,20}},
              textString="p"), Text(
              extent={{20,-20},{80,-80}},
              textString="T")}));
```

**Comment by beutlich** [comment]
Note the ambient icon in https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/Images/UsersGuide/ModelicaLibraries.png
