### ISSUE TITLE
Text position in icons of sensors

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2627]
Similar to #2621, the text in the sensor icons should be placed and sized properly. This concerns (at least some sensors of)
- [x] Modelica.Electrical.Analog.Sensors
- [x] Modelica.Electrical.MultiPhase.Sensors
- [x] Modelica.Electrical.MultiPhase.Sensors
- [x] Modelica.Electrical.QuasiStationary.SinglePhase.Sensors
- [x] Modelica.Fluid.Sensors
- [x] Modelica.Magnetic.FluxTubes.Sensors
- [x] Modelica.Magnetic.FundamentalWave.Sensors
- [x] Modelica.Magnetic.QuasiStatic.FluxTubes.Sensors
- [x] Modelica.Magnetic.QuasiStatic.FundamentalWave.Sensors
- [x] Modelica.Mechanics.Rotational.Sensors
- [x] Modelica.Mechanics.MultiBody.Sensors

**Comment by beutlich** [comment]
@christiankral @tobolar Is this issue also considered by your changes for #2628?

**Comment by tobolar** [comment]
Yes for mechanical sensors. I've ticked it accordingly in my comment above.

**Comment by beutlich** [comment]
@christiankral @tobolar Can this be closed or this there anything left to do?

**Comment by christiankral** [comment]
Yes, it can be closed from my side.

**Comment by beutlich** [comment]
Thanks a lot!
