### ISSUE TITLE
Space Phasor Blocks do not use SpacePhasor connection type

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#2632]
The components in **Modelica.Electrical.Machines.SpacePhasors.Blocks** do not use the connector type **Modelica.Electrical.Machines.Interfaces.SpacePhasor**, as such they cannot be connected to the space phasor ports in **Modelica.Electrical.Machines.SpacePhasors.Components**.  Maybe that is by design, but it is unfortunate.

**Comment by AHaumer** [comment]
This is by design. The blcoks are intended to be used in control. The space phasors of a machine cannot be accessed in real world, they are calculated by measureing e.g. currents and using the transformation block.
