### ISSUE TITLE
Changes to Electrical.Analog icons in 3.2.3

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#2654]
The following commit made a lot of changes to icons in Electrical.Analog: https://github.com/modelica/ModelicaStandardLibrary/commit/232813ba512ea89e71a9f08d9b02c278b8c97756

There are a couple of changes that I am not sure whether they were intentional or not, and the description of the commit(s) does not provide many details. @christiankral (or anyone else who is familiar with the changes), can you please verify that the following icons look as intended and not regressions?
Electrical.Analog.Basic.HeatingResistor (The arrow disappeared)
3.2.2:
![heatingresistor](https://user-images.githubusercontent.com/20460714/41602111-13a22632-73a8-11e8-9c08-f2c301bb5390.png)
3.2.3:
![heatingresistor](https://user-images.githubusercontent.com/20460714/41602125-1ad04fa6-73a8-11e8-8b7c-b75acdc030f9.png)
Electrical.Analog.Basic.M_Transformer (The dotted line disappeared)
3.2.2:
![m_transformer](https://user-images.githubusercontent.com/20460714/41602206-44716d2c-73a8-11e8-9ad4-3cf867eef56e.png)
3.2.3:
![m_transformer](https://user-images.githubusercontent.com/20460714/41602221-4c861c6a-73a8-11e8-9de5-a3e1d2450a17.png)
Electrical.Analog.Ideal.ControlledIdealCommutingSwitch had port labels in 3.2.2 but not in 3.2.3.
3.2.2:
![controlledidealcommutingswitch](https://user-images.githubusercontent.com/20460714/41602563-2334a722-73a9-11e8-8268-92add350a73b.png)
3.2.3:
![controlledidealcommutingswitch](https://user-images.githubusercontent.com/20460714/41602583-302321b6-73a9-11e8-9b79-e86d3ba7a959.png)
Electrical.Analog.Ideal.ControlledIdealIntermediateSwitch had port labels in 3.2.2 but not in 3.2.3.
3.2.2:
![controlledidealintermediateswitch](https://user-images.githubusercontent.com/20460714/41602651-55077d42-73a9-11e8-8005-fef276cc573e.png)
3.2.3:
![controlledidealintermediateswitch](https://user-images.githubusercontent.com/20460714/41602662-5c0288a8-73a9-11e8-8d1d-a9d984c8715a.png)
Electrical.Analog.Ideal.IdealCommutingSwitch had port labels in 3.2.2 but not in 3.2.3.
3.2.2:
![idealcommutingswitch](https://user-images.githubusercontent.com/20460714/41602857-b9ba8342-73a9-11e8-8bf9-aeb9f6d9a5b9.png)
3.2.3:
![idealcommutingswitch](https://user-images.githubusercontent.com/20460714/41602880-c466170c-73a9-11e8-8d1d-0653725d3d7a.png)
Electrical.Analog.Ideal.IdealIntermediateSwitch used to have more lines and port labels.
3.2.2:
![idealintermediateswitch](https://user-images.githubusercontent.com/20460714/41603014-15a7c0fc-73aa-11e8-96be-30b2ae551bad.png)
3.2.3:
![idealintermediateswitch](https://user-images.githubusercontent.com/20460714/41603032-1fc78144-73aa-11e8-94ea-d2fce4ef3f95.png)

**Comment by christiankral** [comment]
The Modelica.Electrical.Analog.Ideal.IdealIntermediateSwitch does not look as intended. For some reason the icon appears on the diagram instead of the icon layer. I will fix this. All other icons look OK.

**Comment by beutlich** [comment]
@christiankral Please explicitly confirm that

- [ ] the removed arrow of the HeatingResistor
- [ ] the removed dotted line in the transformer
- [ ] the removed vertical lines to the top pin in the switches

are by purpose!

**Comment by christiankral** [comment]
Agree: all these changes are made on purpose:
- The arrow is not required as the model is fully compatible to the regular resistor model which does NOT have an arrow
- The dotted line in the transformer model -> minimalistic approach
- The vertical lines to the switches are removed -> minimalistic approach, since it is clear from the symbol which connectors are triggering the switch

**Comment by eshmoylova** [comment]
@christiankral What about port labels on switches? Are they also removed as part of minimalistic approach?

**Comment by christiankral** [comment]
@eshmoylova Yes, this follows the same minimalistic approach: The port labels are removed, since tooltips (in Dymola and OpenModelica) show the instance names of the connectors. However, we do not use port labels in other electrical components, so it makes sense to have these obsolete port labels removed.

**Comment by beutlich** [comment]
Thanks. All questions clarified.

**Comment by tobolar** [comment]
> The port labels are removed, since tooltips (in Dymola and OpenModelica) show the instance names of the connectors.

See also discussion in PR  #2471, which IMO is still open (the discussion, not the PR).
