### ISSUE TITLE
Extra line or missing port in Mechanics.MultiBody.Sensors.RelativeAngles icon

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#2655]
In 3.2.3 the icon for Mechanics.MultiBody.Sensors.RelativeAngles has changed to include an extra line that does not connect to anything and may potentially indicate a missing port.
In 3.2.2:
![relativeangles](https://user-images.githubusercontent.com/20460714/41604803-1070a500-73ae-11e8-8221-812a9f565e21.png)
In 3.2.3:
![relativeangles](https://user-images.githubusercontent.com/20460714/41604811-15ffd11c-73ae-11e8-827d-d0033e4e33df.png)

The line comes from:
https://github.com/modelica/ModelicaStandardLibrary/blob/6f5b87df0a10fe3f2bd2e87fc8263e1e20d5add8/Modelica/Mechanics/MultiBody/Sensors.mo#L1544
that was added in https://github.com/modelica/ModelicaStandardLibrary/commit/cfcdb056c0e1bca136ac3f724c3a936a87057bbd
Before this change the RelativeAngles sensor was the only relative sensor that did not extend from PartialRelativeSensor. With this change it follows the same pattern as other relative sensors with one important exception. In other relative sensors there is usually an extra port connected to that dotted line defined as:
```modelica
    Modelica.Mechanics.MultiBody.Interfaces.Frame_resolve frame_resolve if ...
annotation (Placement(transformation(extent={{84,64},{116,96}})));
```
So, for example, the RelativeVelocity sensor icon is:
![relativevelocity](https://user-images.githubusercontent.com/20460714/41605633-d51d85e8-73af-11e8-9551-e0c96d385631.png)

I believe the reason **frame_resolve** is not included in the definition of the PartialRelativeSensor is that the condition on it changes depending on the type of the sensor.

The question is: Does the RelativeAngles sensor also need to have **frame_resolve** to follow the pattern of other relative sensors? If not, should the line leading to it be present in the icon?

**Comment by tobolar** [comment]
The RelativeAngles doesn't need this transformation since it doesn't deliver a physical vector. PR is in preparation...
