### ISSUE TITLE
No more delay memory available - What does this mean?

### ISSUE THREAD

**Issue by PhilHui** [modelica/ModelicaStandardLibrary#2677]
I get the following message while simulating a large number of district heating consumers and thought someone here might have an idea or experience with this error? 
I am using the operator spatialDistribution()-Operator and get the following error message (nothing else):
```
The following error was detected at time: 0
The maximum number of delays (= 2000) is reached.
No more delay memory is available

FixInitials:Init
```
What i know so far:

- It doesnt seem to be linked to the amount of consumers i try to simulate. I got this error message when i tried to simulate 70 consumers, but also had poor initialisation values. Fixing those fixed the error message and the simulation ran through.

- I dont think its the spatialDistribution()-Operator since i use it 6 times per consumer which would put it well below 2000 for lets say 110 consumers (which is the amount where i get the error right now)

**Comment by beutlich** [comment]
There is no spatialDistribution called in MSL.
