### ISSUE TITLE
Further improvements of toUpperHessenberg

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#2692]
So that we don't miss the items detected in #2691 (these also apply to the related functions).

- Missing test-cases for non-default ilo, ihi.

- Documentation of ilo and ihi is unclear; basically the matrix is in supposed to be in BLT-form where the parts before and after ilo:ihi are already upper triangular and we only have to transform that sub-matrix.

In retrospect not exposing ilo and ihi had probably been a wiser choice, but removing them now seems more problematic.
(Removing the last column of V just seems to cause problems for no real gain.)

**Comment by beutlich** [comment]
@HansOlsson Friendly reminder.
