### ISSUE TITLE
FluidHeatFlow: PumpTurbine

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#2699]
FluidHeatFlow: newly introduced PumpTurbine has to be removed before releasing 3.2.3, otherwise correcting the equations is not possible in a backwards compatible way, better introdue later

**Comment by beutlich** [comment]
PumpTurbine was introduced by 0ade4359bd76c44cfd6d20e3102f606fd6283708, thus v3.2.3-beta.1.
