### ISSUE TITLE
ModelicaReference.Annotations.Documentation contains unresolvable URIs

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaStandardLibrary#2721]
The documentation in `ModelicaReference.Annotations.Dialog` contains two instances of `modelica://Multibody...`. I believe these should be `modelica://Modelica/Multibody/...` to resolve correctly.

**Comment by sjoelund** [comment]
https://github.com/modelica/ModelicaStandardLibrary/blob/467a0b68f7f3fb455cda84583d6f6b20db9f45a8/ModelicaReference/package.mo#L760
is not a link though. It could refer to anything, and I suppose in this instance it referred to the old MultiBody library. I suppose this link should be `modelica://Modelica.Mechanics.MultiBody.UsersGuide.Tutorial` to resolve correctly (didn't check MSL to see the new location).

**Comment by dietmarw** [comment]
Yes that location is correct. But it does not have to be an existing Package in this **example* snippet. I will supply a PR which changes this to a URI that does not indicate an existing package.
