### ISSUE TITLE
ModelicaReference.Annotations.Dialog contains an unresolvable URI

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaStandardLibrary#2722]
The documentation in `ModelicaReference.Annotations.Dialog` contains `modelica://MyPackage/Resources/Images/image.png`. I realize this is an example, but there is no indication that this URI is not to be resolved, so a tool that is generating the documentation will try to do so.

**Comment by usn-student** [comment]
I agree with @sjoelund that this is a non-issue.

**Comment by dietmarw** [comment]
I agree with @sjoelund that this is a non-issue.
