### ISSUE TITLE
No medium2 in Modelica.Media.Examples.MoistAir

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2743]
Documentation of Modelica.Media.Examples.MoistAir mentions medium2, but there is no such second medium in the example model.

https://github.com/modelica/ModelicaStandardLibrary/blob/d053d332d61fd754e44bf680a8f80bde76d24315/Modelica/Media/package.mo#L2424-L2430

**Comment by dietmarw** [comment]
I looked at this and it seems the documentation of `MoistAir` belongs actually into `MixtureGases`. Then also the reference to `medium2` makes sense. I could have simply moved the documentation over but then I'm not sure what the documentation for `MoistAir` should look like. @hubertus65 any suggestions?

PS: Duplicates of these models also exist in ModelicaTest and should probably be updated at the same time.

**Comment by HansOlsson** [comment]
> PS: Duplicates of these models also exist in ModelicaTest and should probably be updated at the same time

Hmm.. That made me realize something:

Why do we have duplicates?
If we only want to test ModelicaTest, and not examples in MSL why duplicate it instead of just making a model in ModelicaTest that extends from the example?

**Comment by dietmarw** [comment]
Yes that would make much more sense.

**Comment by beutlich** [comment]
These duplicates should be sorted out by #1053, #2542 and #2745.

**Comment by beutlich** [comment]
> I looked at this and it seems the documentation of `MoistAir` belongs actually into `MixtureGases`.

No, it was copied from IdealGasH2O.
