### ISSUE TITLE
Use quoted section for preformated text

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#2752]
I suggest to quote sections of preformated text in the documentation, in HTML by `<blockquote> ... </blockquote>`. This is already established in plenty of classes, but not consequently in all classes.
If agreed, this should especially be documented in `Modelica.UsersGuide.Conventions.Documentation.Format.Code`.

**Comment by tobolar** [comment]
I found out there is right opposite definition in `Modelica.UsersGuide.Conventions.Documentation.Format.Code`:
> 3. Multi line or single line code shall not be indented.

But I still believe the text in the second figure below is better readable than the text in the first figure and vote for changing this rule.
<hr>

**Figure 1** - snapshot of the current "Code" document:


> ![grafik](https://user-images.githubusercontent.com/9588978/47709443-8738fd00-dc30-11e8-84fa-8dbc66c58d37.png)

**Figure 2** - the same document, code lines formated using blockquote:

> ![grafik](https://user-images.githubusercontent.com/9588978/47709452-8c964780-dc30-11e8-93ba-d6272e74c684.png)

**Comment by beutlich** [comment]
Are the blockquote tags missing in the 2nd example of the 2nd figure? Otherwise I wonder why it is indented w.r.t. the 1st figure.

**Comment by tobolar** [comment]
@beutlich Fixed 2nd figure.

**Comment by beutlich** [comment]
@tobolar Seems accepted.

1. Can you please update the conventions! Thanks.
1. Do we also want to fix it in current MSL for v4.0.0?

**Comment by tobolar** [comment]
> 2. Do we also want to fix it in current MSL for v4.0.0?

You mean to go through all &lt;pre&gt;s?

**Comment by beutlich** [comment]
> 
> 
> > 1. Do we also want to fix it in current MSL for v4.0.0?
> 
> You mean to go through all <pre>s?

Yes.

**Comment by tobolar** [comment]
OK, I will look over it.
