### ISSUE TITLE
Missing component descriptions in example ShowTransferFunction

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2761]
Parameters a, b, d, wMax, wMin and variables dB, lg_w and phi miss a descriptive string.

See also #2166 and #1850.

**Comment by AHaumer** [comment]
d: damping coefficient
b: numerator polynomial coefficients of transfer function
a: denominator polynomial coefficients of transfer function
wMin: lower bound for frequency sweep
wMax: upper bound for frequency sweep
lg_w: logarithm of frequency
dB: absolute of transfer function in decibel
phi: argument of transfer function

**Comment by beutlich** [comment]
Thanks.

> dB: absolute of transfer function in decibel

Modified to magnitude in #2767. Please review.

**Comment by beutlich** [comment]
> 
> 
> Please mark this also in #2636, if finished!

Done.
