### ISSUE TITLE
Unit conversion bug in Media.IdealGases.Common.MixtureGasNasa.mixtureViscosityChung

### ISSUE THREAD

**Issue by finback-at** [modelica/ModelicaStandardLibrary#2764]
The output value of mixtureViscosityChung for CombustionAir is in the order of 1e+9. Too large!
I checked the original document.
The unit of calculated value of etam is 

    (micro Poise) = 1e-7 (Pa.s)

Current output value is

`
   etaMixture := etam*1e7;
`

It should be corrected to,

`
etaMixture := etam*1e-7;
`

**Comment by beutlich** [comment]
@thorade Are you familar with https://github.com/modelica/ModelicaStandardLibrary/blob/71590c7e658a6fbbe037364f52b82589b01a1003/Modelica/Media/IdealGases/Common/package.mo#L1061 ?

**Comment by thorade** [comment]
Sorry, I have not used that correlation myself. The three references given are:
Chung 1988 https://doi.org/10.1021/ie00076a024
Chung 1984 https://doi.org/10.1021/i100013a002
general reference, book by Poling https://scholar.google.com/scholar?cluster=5190098174187723396

The unit used by default in MSL is Pa.s which is inconvenient for viscosity, a displayUnit µPa·s would be nice, also see #545.
https://en.wikipedia.org/wiki/Viscosity#Units
