### ISSUE TITLE
Set copyright holder to Modelica Association everywhere

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2787]
@GallLeo Can you please clarify the MSL copyright holders once the CLAs have been signed.

@hubertus65 @MartinOtter FYI

**Comment by GallLeo** [comment]
After discussion with @MartinOtter and @beutlich: Workflow seems not be clarified until now. Needs to be fixed within MAP-LIB.

Solution needs to display contributions on Github (LICENSE) as well as within Modelica code and Info Layer of MSL.
