### ISSUE TITLE
Missing parameters in Spice3.Sources.I_pwl and V_pwl

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#2790]
The html documentation for the Spice3 current and voltage pwl sources mention startTime and offset parameters; they do not exist in the models.

**Comment by beutlich** [comment]
#2791 fixes only the documentation.

Could be also possible to add the parameters timeScale, startTime, offset and shiftTime from Modelica.Blocks.Sources.TimeTable to I_pwl/V_pwl.

**Comment by beutlich** [comment]
> Could be also possible to add the parameters timeScale, startTime, offset and shiftTime from Modelica.Blocks.Sources.TimeTable to I_pwl/V_pwl.

@JoeRiel Please open new issue if this should rather be fixed as proposed above.
