### ISSUE TITLE
Spice3 Constant Current source has no arrow

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#2792]
The symbol for Modelica.Electrical.Spice3.Sources.I_constant has no arrow, unlike the other current sources.  One has to use the solid/open ports to determine the prescribed flow direction, which is less clear and less convenient.

**Comment by beutlich** [comment]
In fact, every icon looks slightly different w.r.t. to the blue circle and the position of the instance name.

**Comment by beutlich** [comment]
And, while working on the Spice3.Sources, we should also fix the assignment of instance name and primary parameter:

![2018-12-06 11_10_26-dymola - dynamic modeling laboratory - diagram](https://user-images.githubusercontent.com/14896695/49577442-ad487000-f947-11e8-8dd7-fefde8a36ff2.png)
