### ISSUE TITLE
Use min/max for k in Modelica.Electrical.Spice3.Basic.K_CoupledInductors

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#2796]
Looking at #2789 I found that we have:
```
  parameter Real k( start=0) "Coupling Factor";
equation 
  assert(k>=0,"Coupling factor must be not negative");
  assert(k<1,"coupling factor must be less than one");
```
I would propose to change the definition to:
`  parameter Real k( start=0, min=0, max=1) "Coupling Factor";`
To detect issues earlier. (And keep the assertions just in case.)

Note that this is different from #2775 that says that k=1 should be allowed, but they can be resolved together.

**Comment by beutlich** [comment]
Confirmed. The maximum attribute set to 1 only is a clean fix, if we allow k=1 by #2775.
