### ISSUE TITLE
Fix documentation of Translational User's Guide

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#2813]
Some documentation issue apply to:

- `Modelica.Mechanics.Translational.UsersGuide.Overview` 
- `Modelica.Mechanics.Translational.UsersGuide.SignConventions`
- `Modelica.Mechanics.Translational.UsersGuide.UserDefinedComponents`

The documentation text refers to:

- component `m1`
- component `m2`

Example: 
![image](https://user-images.githubusercontent.com/4184218/51635749-d6ed4300-1f57-11e9-8bff-a6151d8e4fa9.png)

The depicted figures however show the components `mass1` and `mass2`. On my opinion this is misleading, as the shown component names of the figures and the text shall match. Otherwise it has to be explained what `m1` and `m2` are compared to `mass1` and `mass2`. This shall be fixed.

**Comment by beutlich** [comment]
I removed the V: 3.2.3-beta.2 label since the issue also is present in earlier MSL versions and did not originate in V: 3.2.3-beta.2.

**Comment by beutlich** [comment]
I changed the milestone for MSL4.0.0 since this is not a servere issue that needs back-porting for MSL 3.2.3.
