### ISSUE TITLE
Misleading doc string of force and torque sources

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#2814]
### Translational

In the model

- `Modelica.Mechanics.Translational.Sources.ConstantForce` 

the parameter 

```
parameter Modelica.SIunits.Force f_constant
    "Nominal force (if negative, force is acting as load)";
```

is used. This is somehow misleading as the negative force of the model only acts as load if the velocity is positive. For negative velocities, a negative force `f_constant` causes the model to generate power. Therefore, it is actually a matter of the quadrant in which the model operates (gray quadrants = not load). 
![image](https://user-images.githubusercontent.com/4184218/51638062-b1633800-1f5d-11e9-97a3-c20726f0a3f9.png)
It thus makes sense to replace the doc string by, e.g.,  `"Nominal force (if negative, force is acting as load in positive direction of motion"`

In model `Modelica.Mechanics.Translational.Sources.SignForce` the same parameter with the same doc string is used, but the text is correct as the model always acts as load if `f_constant` is negative.

The models 

- `Modelica.Mechanics.Translational.Sources.LinearSpeedDependentForce`
- `Modelica.Mechanics.Translational.Sources.QuadraticSpeedDependentForce`

use the additional Boolean parameter `ForceDirection` to adapt the model behavior. Yet the negative sign of the force again refers to quadrant IV. Therefore the doc string might also be changed.

### Rotational

In model `Modelica.Mechanics.Rotational.Sources.ConstantTorque` the doc string of parameter `tau_constant` is correct: `"Constant torque (if negative, torque is acting as load in positive direction of rotation)"`. The same doc string is used for model `Modelica.Mechanics.Rotational.Sources.SignTorque`: in this case the "positive direction of rotation" does not apply, as it always behaves as load of the nominal torque is negative. The doc string `"Nominal torque (if negative, torque is acting as load)"` of the models

- `Modelica.Mechanics.Rotational.Sources.LinearSpeedDependentTorque`
- `Modelica.Mechanics.Rotational.Sources.QuadraticSpeedDependentTorque`

is not correct, however, as it again refers to quadrant IV only.

**Comment by beutlich** [comment]
I changed the milestone for MSL4.0.0 since this is not a servere issue that needs back-porting for MSL 3.2.3.

**Comment by tobolar** [comment]
Comparing the forces of the abovementioned translational components against speed:
![translForcesCompare](https://user-images.githubusercontent.com/9588978/54118103-9310a900-43f2-11e9-94d6-c37203040b0f.png)
