### ISSUE TITLE
Migrate FluidHeatFlow to stream-concept

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#282]
**Reported by AHaumer on 12 Feb 2010 14:31 UTC**
What are the consequences?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/282

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 16 Jul 2010 11:51 UTC**
It is important to change this soon. This is a non-backward compatible change that cannot be handled with conversion scripts, since too many changes. The only meaningful was is:

 1. Move FluidHeatFlow to library ObsoleteModelica.
 2. Provide a conversion script that changes user models from
    Modelica.Thermal.FluidHeatFlow to ObsoleteModelica.Thermal.FluidHeatFlow. 
 3. Provide a new FluidHeatFlow where the stream operator is used

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 2 Mar 2012 09:04 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by beutlich** [comment]
@AHaumer This is of low priority though it was considered to be dealt with rather soon. I also doubt that you intend to move the current FluidHeatFlow to ObsoleteModelica. Thus, after all, is this still a feasible goal for MSL v4.0.0 with about 6 months before feature freeze?

**Comment by AHaumer** [comment]
In the meantime I changed my mind: FluidHeatFlow should keep using semiLinear instead of the stream concept. Therefore closing the ticket.
