### ISSUE TITLE
Update ModelicaReference to latest Modelica specification 3.4

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#2820]
ModelicaReference is based on MLS 3.2 (not even sure which revision), but should be updated to MLS 3.4.

**Comment by HansOlsson** [comment]
Makes sense, will see when I get time, and I assume it is best to ensure that the version on maint/3.2.3 uses MLS 3.2r2 as the rest. 
I realized that we should also update https://github.com/modelica/Modelica-Compliance to MLS 3.4; and it may make sense to update both together (in the sense that changes are both described and tested).

**Comment by beutlich** [comment]
Seehttps://htmlpreview.github.io/?https://github.com/modelica-tools/ModelicaSyntaxChecker/blob/master/Grammar.html for the grammar.

**Comment by beutlich** [comment]
@dietmarw @HansOlsson Do you think you can manage to update the ModelicaReference?

**Comment by dietmarw** [comment]
@svorkoetter Could you provide the updated "Modelica Grammar" also including fixes to HTML issues that were mentioned earlier. Feel free to submit it as PR to https://github.com/modelica-tools/ModelicaSyntaxChecker (including updated moparser binary if you got them). Thanks.

**Comment by dietmarw** [comment]
@HansOlsson since you are working most intense with the Specs I wonder if you can list the new/changed parts from Spec 3.2 to 3.4 that are relevant for Modelica Refernece. Otherwise I need to go through the documents with revision marks and chances are I might miss some central items/changes.

**Comment by HansOlsson** [comment]
I will try to do it, I just started with looking at Modelica-Compliance (well, after looking at issues for the specification itself).

**Comment by svorkoetter** [comment]
Will do. Just so I'm sure to get the right grammar, what's the official source of the up-to-date spec?

On Fri, 27 Sep 2019 02:03:17 -0700
Dietmar Winkler <notifications@github.com> wrote:

> @svorkoetter Could you provide the updated "Modelica Grammar" also
> including fixes to HTML issues that were mentioned earlier. Feel free
> to submit it as PR to
> https://github.com/modelica-tools/ModelicaSyntaxChecker (including
> updated moparser binary if you got them). Thanks.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/modelica/ModelicaStandardLibrary/issues/2820#issuecomment-535857579


-- 
Stefan Vorkoetter
Senior Architect
Maplesoft

**Comment by HansOlsson** [comment]
> Will do. Just so I'm sure to get the right grammar, what's the official source of the up-to-date spec?

Do you mean https://github.com/modelica/ModelicaSpecification
which has links to PDF and HTML-versions, both for master-branch and 3.4.

**Comment by svorkoetter** [comment]
@HansOlsson, has the grammar changed since the time that I already uploaded the requested files?

**Comment by beutlich** [comment]
@svorkoetter Can you please create a PR updating the grammar to specification 3.4. See https://specification.modelica.org/v3.4/A2.html#grammar for the reference to take it from.

**Comment by beutlich** [comment]
> has the grammar changed since the time that I already uploaded the requested files?

Yes, it did. Take the pure/impure class-prefixes as example.

**Comment by beutlich** [comment]
@HansOlsson Should the clocked/synchronous language elements also be added to ModelicaReference?

**Comment by HansOlsson** [comment]
> @HansOlsson Should the clocked/synchronous language elements also be added to ModelicaReference?

I believe so, especially since we are adding Modelica.Clocked. 
Note that the state-machine part can be skipped at the moment.

Adding sample, hold etc in the list of operators would be straightforward; but it is not clear if we should add a general overview - and if so how detailed. If we add it my preference would be to keep it very short - so just a one (or two) paragraph summary, since it is complicated to maintain ModelicaReference as a duplicated variant of the specification.

**Comment by beutlich** [comment]
> If we add it my preference would be to keep it very short

Yes, please!

**Comment by svorkoetter** [comment]
> Yes, it did. Take the pure/impure class-prefixes for example.

That was already there. The only changes seem to be the missing closing `</p>` tags, and the change from `annotation` to `annotation_comment`.

**Comment by beutlich** [comment]
The syntax of the keywords, e.g. in [ModelicaReference.'import'](https://doc.modelica.org/ModelicaReference%203.2.3/Resources/helpDymola/ModelicaReference.html#ModelicaReference.'import') is

* a partial duplication of the [Modelica Grammar](https://doc.modelica.org/ModelicaReference%203.2.3/Resources/helpDymola/ModelicaReference.html#ModelicaReference.ModelicaGrammar)
* outdated, since it still is for Modelica language 3.2

Can we savely remove it to avoid the extra maintenance and link to ModelicaReference.ModelicaGrammar instead? Unfortunetaly, it currently is not possible to refer to anchor links within modelica URIs, see https://github.com/modelica/ModelicaSpecification/issues/2445 for the corresponding specification issue.

**Comment by dietmarw** [comment]
I agree. Instead of listing the syntax we should simply point to `ModelicaRerence.ModelicaGrammar`.  In a addition the example should be changed since it demonstrates the usage of wildcard imports, something that we at the same time emphasise to not use.
