### ISSUE TITLE
Missing consts in  ModelicaStandardTables_CombiTimeTable_init2 prototype

### ISSUE THREAD

**Issue by d94pn** [modelica/ModelicaStandardLibrary#2842]
In ModelicaStandardTables_CombiTimeTable_init2 the following arguments should be const according to:

-  **const** double* table
-  **const** int* columns

Note also that in the C file (implementation part) the "columns" argument is renamed to "cols".

The same applies to:

- ModelicaStandardTables_CombiTimeTable_init 
- ModelicaStandardTables_CombiTable1D_init
- ModelicaStandardTables_CombiTable2D_init

**Comment by beutlich** [comment]
> In ModelicaStandardTables_CombiTimeTable_init2 the following arguments should be const according to:
> 
>     * **const** double* table
> 
>     * **const** int* columns
> 

No, this would be in violation to the Modelica Specification 3.x, see section [12.9.1.2](https://specification.modelica.org/master/Ch12.html#arrays-1).

> Note also that in the C file (implementation part) the "columns" argument is renamed to "cols".
> 
> The same applies to:
> 
>     * ModelicaStandardTables_CombiTimeTable_init
> 
>     * ModelicaStandardTables_CombiTable1D_init
> 
>     * ModelicaStandardTables_CombiTable2D_init

Agreed. Declaration and definition should use identical argument names.
