### ISSUE TITLE
Axis for ModelicaTest.MultiBody.Joints.UniversalSpherical

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#2866]
Based on https://github.com/modelica/ModelicaStandardLibrary/issues/2720#issuecomment-477157967
as far as I can tell there are three variants in ModelicaTest.MultiBody.Joints.UniversalSpherical of universal+rod+spherical, and it is checked they generate the same result.

However, the middle one seems to have strange axis, a different n1 ({1,0,0}) that is co-linear with the rod-axis. I would propose to change it to {0,0,1} as the other two variants and change start-value back to zero.

**Comment by MartinOtter** [comment]
There is no "n1" defined. Can you give a more detailed description based on oject names (e.g. universal.n_a should be changed from xxx to yyy).

**Comment by HansOlsson** [comment]
> There is no "n1" defined and your statement is not clear.

That was correct in the linked comment:
https://github.com/modelica/ModelicaStandardLibrary/issues/2720#issuecomment-477080461

I meant that both `universalSpherical.n1_a={0,0,1}` and `universalSpherical1.n1_a={0,0,1}` but `universal.n_a={1,0,0}` which is both different and co-linear with `fixedTranslation.r`.

Thus I propose to change `universal.n_a={0,0,1}`, and reverting the change of `universal.phi_a `back to zero.

If this isn't correct there should be some additional comments; because it clearly seems that the intent is to ensure that three different variants give the same result.

**Comment by MartinOtter** [comment]
Yes, you are right (so to change to universal.n_a={0,0,1}, and reverting the change of universal.phi_a back to zero).

**Comment by MartinOtter** [comment]
@tobolar: Please, can you perform this change.

**Comment by tobolar** [comment]
Will do it.
