### ISSUE TITLE
Modelia.Media.Air.MoistAir.s_pTX_der is not right

### ISSUE THREAD

**Issue by finback-at** [modelica/ModelicaStandardLibrary#2874]
[s_pTX_der.pdf](https://github.com/modelica/ModelicaStandardLibrary/files/3035944/s_pTX_der.pdf)

I think MoistAir.s_pTX_der is not right.
Please see above PDF.

**Comment by beutlich** [comment]
Related to #2872.

**Comment by wischhusen** [comment]
Corrected the code accordingly. @finback-at Many thanks for the calculations!
