### ISSUE TITLE
Machines airGap

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#289]
**Reported by AHaumer on 14 Feb 2010 10:25 UTC**
When a conversion script is allowed, rename the airGaps in the machine models without a trailing character to have the chance to move the airGap to the partial machine model and make it replaceable.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/289

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 2 Mar 2012 09:05 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 20 Dec 2016 16:41 UTC**

**Comment by modelica-trac-importer** [comment]
**Changelog removed by ahaumer on 20 Dec 2016 16:41 UTC**

**Comment by AHaumer** [comment]
After PR #3045 (thanks to @beutlich ) is merged, we plan to move Machines.BasicMachines.Components.{PartialAirGap, PartialAirGapDC, PartialCore} to Machines.Interfaces.
@christiankral should we have a sub-library BaseClasses, keeping in Interfaces only {SpacePhasor, FlangeSupport, ThermalPort$, PowerBalance$}?
