### ISSUE TITLE
ModelicaMatIO.c conversion warnings

### ISSUE THREAD

**Issue by GarronFish** [modelica/ModelicaStandardLibrary#2905]
When compiling a model that makes use of ModelicaMatIO.c I get the following warnings:
C:\Program Files\Dymola 2020 Beta 3\Source\ModelicaMatIO.c(6615): warning C4244: '=': conversion from 'size_t' to 'double', possible loss of data
C:\Program Files\Dymola 2020 Beta 3\Source\ModelicaMatIO.c(6624): warning C4244: '=': conversion from 'size_t' to 'double', possible loss of data

These warnings are due to the lines 6615 and 6624 in ModelicaMatIO.c:
tmp = matvar->dims[0];
and
tmp = matvar->dims[1];

I suggest that the following be used 
tmp = (double)matvar->dims[0];
and
tmp = (double)matvar->dims[1];

**Comment by beutlich** [comment]
This is an upstream issue of [matio](https://github.com/tbeu/matio). It will be fixed once a new version of matio is released and and merged into ModelicaMatIO.
