### ISSUE TITLE
Removing usage of Clock as a class name and component name

### ISSUE THREAD

**Issue by Daiwen** [modelica/ModelicaStandardLibrary#2945]
I would like to propose that we modify the MSL to not use `Clock` as a class name. This would resolve some ambiguities for the user, and make it possible for the language design group to make `Clock` a keyword of the Modelica language.

Conversion rules would make that change somewhat easier.

**Comment by beutlich** [comment]
@Daiwen Should https://github.com/modelica/ModelicaSpecification/issues/2280 be reopened?

**Comment by henrikt-ma** [comment]
Before reopening https://github.com/modelica/ModelicaSpecification/issues/2280, I suggest a small scope creep of this issue to cover all introduced `Clock` identifiers in the MSL.  As long as the MSL has components called `Clock`, there's still nothing we can do about it's keyword status.

**Comment by Daiwen** [comment]
I hadn't seen the case of component names but Henrik is right we can't reopen  modelica/ModelicaSpecification#2280 until there are still occurrences of `Clock` whatever they maybe.
I can open a new issue if you'd prefer me doing it that way.

**Comment by beutlich** [comment]
OK, I got it.
