### ISSUE TITLE
PowerConverters DC/DC

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#2953]
I'd recommend to enhance the DC/DC-examples of Modelica.Electrical.PowerConverters:
- add inductor and smoothing capacitor to StepDown
- delete example StepDown_RL
- change default parameterization of StepDown and StepUp
This makes the examples more realistic and comparable:
- StepDown results in 60 V -> 12 V / 1.2 A
- StepUp results in 60 V -> 75 V / 1.2 A

**Comment by AHaumer** [comment]
see PR #2955

**Comment by beutlich** [comment]
After closing #2955 w/o merge, is this now covered by #2970?

**Comment by beutlich** [comment]
I believe it is resolved by #2970. Please reopen otherwise.
