### ISSUE TITLE
Inquiries about C_outflow in the FluidPort

### ISSUE THREAD

**Issue by KooJagun** [modelica/ModelicaStandardLibrary#2962]
Hi, i'm noob for modelica and developing the Heat Exchanger model.
I encountered some errors like captures below.
![2](https://user-images.githubusercontent.com/13636830/59084345-d321f200-8935-11e9-9967-7b0ddde2431f.jpg)
![1](https://user-images.githubusercontent.com/13636830/59084350-d61ce280-8935-11e9-9d0f-07a483958c12.jpg)

First, i don't know what is the physical meaning of C_outflow. I could find that C_outflow = c_i/m
and m is the mass of the fluid, but couldn't find the meaning of c_i.
Second, i've just tried to input the value 0~1 as the description said, but encountered the error message above. I think the value has not been input to the C_outflow array but i'm not sure.

Please reply anyone who can figure out these problems... Thank you to all of you.

**Comment by dietmarw** [comment]
The issue tracker is for issues regarding the development of the MSL. For modelling help you should use: https://stackoverflow.com/tags/modelica
