### ISSUE TITLE
Rename MultiPhase to Polyphase

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaStandardLibrary#2973]
This is a follow-up on https://github.com/modelica/ModelicaStandardLibrary/issues/1865#issuecomment-330878902 and also related to #733 and also #2971.

We should correct the multi-phase terms (and their spelling variants) to `Polyphase`. Mind no camel case since it was agreed that the correct to be used term is "polyphase" and not "poly-phase" or "poly phase".

**Comment by beutlich** [comment]
I started to work on it. It is getting massive.
