### ISSUE TITLE
ModelicaInternal_fullPathName truncates trailing '/' on Linux

### ISSUE THREAD

**Issue by d94pn** [modelica/ModelicaStandardLibrary#3003]
The function ModelicaInternal_fullPathName truncates trailing '/' on Linux, but not on Windows.
The truncating behavior in the Linux realpath needs to be compensated for, by checking for existing trailing '/' in the input argument and then add this later to the resulting fullName if needed.

**Comment by beutlich** [comment]
This is due to realpath behaving differently than _fullpath.

During test, I also discovered another issue (of uninitialized memory returned by ModelicaAllocateString) in the _POSIX_ branch. This also is addressed by #3004.
