### ISSUE TITLE
Change parameter freqHz to f

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#3035]
The parameter `freqHz` of the sinusoidal voltage sources of

* `Modelica.Electrical.Analog.Sources`
* `Modelica.Electrical.MultiPhase.Sources`

shall be changed to `f`

**Comment by christiankral** [comment]
Before doing this ticket, #2973 shall be done.

**Comment by AHaumer** [comment]
In favour!

**Comment by beutlich** [comment]
> 
> 
> Before doing this ticket, #2973 shall be done.

Merged.

**Comment by christiankral** [comment]
This issue also affects the following components in `Modelica.Blocks.Sources`

* `Sine`
* `Cosine`
* `ExpSine`

**Comment by beutlich** [comment]
Resolved by #3046.
