### ISSUE TITLE
update Labels

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#3055]
@beutlich Shouldn't we update Labels at GitHub?
Electrical.QuasiStationary -> Electrical.QuasiStatic
Electrical.MultiPhase -> Electrical.PolyPhase
I know the old terms are used in 3,2,3 but shouldn't we switch to the new terms?
I'm pretty sure I forgot some Labels ...
Furthermore, wouldn't it be usefull to have "top level" Labels like "Blocks", "Electrical", ...

**Comment by AHaumer** [comment]
Maybe for some time we use 
Electrical.QuasiStatic/QuasiStationary
Electrical.PolyPhase/MultiPhase

**Comment by beutlich** [comment]
I already thought about it. The issue is that I generate the ResolvedGitHubIssues.html from the closed issues and sort by labels. If I do it for MSL v3.2.3+build.3 I still need the old labels. Thus I have no real idea and left it as is.

**Comment by AHaumer** [comment]
Is using old and new labels in prallel the solution?
Old labels -> 3.2.3, new labels -> >4.0.0

**Comment by beutlich** [comment]
That would work out (and keeps me busy with relabeling).

**Comment by beutlich** [comment]
Done. Added new labels and relabeled all open and closed issues/PRs w.r.t. the new labels.
