### ISSUE TITLE
Coding / Naming guidelines

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#3057]
There's a lot of discussion about coding and naming guidelines. 
Just a question:
How to represent a variable from a textbook with an underscore as a Modelica variable?
Widely used for Complex variables.
![grafik](https://user-images.githubusercontent.com/6900273/61386781-2da75a00-a8b5-11e9-9d4b-84c8e964b28b.png)
How to represent a variable with a line as accent ("upperscore", I don't know the right term) as a Modelica variable?
Widely used for the arithmetic mean of a variable or as the negated variable.
![grafik](https://user-images.githubusercontent.com/6900273/61387041-9f7fa380-a8b5-11e9-81e6-ba5f3623950e.png)
@beutlich @dietmarw @christiankral @tobolar ... - any idea?

**Comment by christiankral** [comment]
This topic is related with https://github.com/modelica/ModelicaSpecification/issues/2357

**Comment by beutlich** [comment]
I think the issue is not feasible for MSL v4.0.0 at all.

I also think that modelica/ModelicaSpecification#2357 is the right space to discuss it together with the Wolfram guys (@henrikt-ma, @maltelenz) who do it right in Mathematica.

**Comment by AHaumer** [comment]
appended to modelica/ModelicaSpecification#2357
