### ISSUE TITLE
Change of DC machine record dialog

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#3079]
Changes of #3072 shall also be applied to the parameter records of the DC machines.

**Comment by beutlich** [comment]
As a hint - since you self-assigned this issue: It would be OK to only create the PR w/o creating a connected issue first.

**Comment by christiankral** [comment]
Thanks for the hint. I would usually create just a PR for small issues. Yesterday I had no time to perform the PR even though it's not much work. I yet wanted keep the information somewhere.
