### ISSUE TITLE
Fluid Examples. HT wall model.

### ISSUE THREAD

**Issue by Ciobrelis** [modelica/ModelicaStandardLibrary#3102]
I have tried to reuse the wall HT model that is provided in the fluid examples. In the scenario that I have 5 volumes and I enable temperatures values at the start, I get an error. 

![image](https://user-images.githubusercontent.com/34867742/63849458-6cd7c900-c992-11e9-8a5f-87b0aca5f129.png)

### **Error:**
![image](https://user-images.githubusercontent.com/34867742/63849645-ccce6f80-c992-11e9-90f2-63823e9bd8aa.png)

I think there is missing some logic / code behind the model, that it would automatically use the fill(value,n) function. So in case, I add it, I get:

![image](https://user-images.githubusercontent.com/34867742/63850002-7dd50a00-c993-11e9-94ea-e600e8ce545d.png)
![image](https://user-images.githubusercontent.com/34867742/63850080-9b09d880-c993-11e9-9596-4d93554545f5.png)

Which basically requires one to manually also add fill() function for Boolean. In this case to add fill(true,nNodes) in multiple lines. for T, Ta and Tb. 

![image](https://user-images.githubusercontent.com/34867742/63850418-47e45580-c994-11e9-802c-7a0e7ebd4d77.png)

Lastly, if you enter the wall model via Diagram view, all fill() functions for Boolean reset, and then one has to enter it again via Text view. 

I hope it is clear. 

The model that I am trying to reuse is: Modelica.Fluid.Examples.HeatExchanger.BaseClasses.WallConstProps

**Comment by beutlich** [comment]
This is not specific to your application. Consider
```mo
model M
  parameter Real p[5];
end M;
```
You cannot pass a scalar to p, but need to provide a vector in all cases, for example using fill. So it either is a specification issue (if we allow assignments between arrays and scalars) or a tool issue (to better guide you in modeling comfort).

**Comment by casella** [comment]
This is not a problem with the Modelica Standard Library, but rather a missing feature of OpenModelica, which has no way to add the `each` prefix to specify parameter arrays by just giving one value which is used for all elements of the array.

Please follow [#5405](https://trac.openmodelica.org/OpenModelica/ticket/5405) on the OpenModelica trac.
