### ISSUE TITLE
Annotations 'tab' and 'group' in Camel Case

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#3103]
Text indicated by the annotation **tab** is in some components Camel Case (e.g. _Internal Interface_ for `Medium` in `Modelica.Fluid.Machines.BaseClasses.PumpMonitoring.PumpMonitoringBase`), in some not (e.g. _Nominal resistances and inductances_ for `Lrsigma` in `Modelica.Electrical.Machines.BasicMachines.InductionMachines.IM_SlipRing`).

Similar mixing holds probably for the annotation **group** as well (I didn't check.).

**Comment by beutlich** [comment]
Any preferences? I'd prefer to change "Internal Interface" to "Internal interface".

**Comment by DagBruck** [comment]
Not the biggest problem in the world, but my #1 preference is consistency.

I think most design guidelines I have seen suggest writing it as a normal sentence, i.e. "Internal interface".

**Comment by tobolar** [comment]
> ... my No.1 preference is consistency.

That's the point of this issue.

I have _slight_ preference to use Came Case in tabs and "sentence-like" style in groups.
Tab's text is mostly short, containing just a guide word(s). I've check in web some screenshots of other software and my impression is that this is handled quite differently:
https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-tabs
https://www.trueos.org/blog/lumina-screenshot-simple-utility-powerful-results/
https://blog.cloudhq.net/send-screenshots/
https://www.tightvnc.com/screenshots.php

**Comment by DagBruck** [comment]
> https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-tabs

But that reference actually recommends "Use sentence-style capitalization", see the section Labels near the end. And their example follow that.

**Comment by tobolar** [comment]
Fine to me. Their guidelines are quite clear and comprehensive so we could simply adopt it.
