### ISSUE TITLE
Icon of Modelica.Mechanics.MultiBody.Joints

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#3104]
Based on comments in #3087 on icon for `Joints` package, here is a concluded suggestion: model `IconForJoints.Joints4a` in https://gist.github.com/tobolar/95e62615d30ed5931cfd94c245040756

In Dymola: 
![jointsIcon_dymola](https://user-images.githubusercontent.com/9588978/64173612-fa665d80-ce57-11e9-8e9c-cab9795badd4.png)

@maltelenz @henrikt-ma @beutlich: Please check if acceptable rendering can be achieved in other tools.

**Comment by beutlich** [comment]
Here's the screen shot from SimulationX

![grafik](https://user-images.githubusercontent.com/14896695/64175320-57afde00-ce5b-11e9-8b0d-8f1b17fd2866.png)

But there is a typo rotatio -> rotation in line 9. And there is invalid inheritance in Joints4a and Joints7.

**Comment by tobolar** [comment]
> But there is a typo rotatio -> rotation in line 9. And there is invalid inheritance in Joints4a and Joints7.

I will fix it eventually for PR.

**Comment by maltelenz** [comment]
SystemModeler:
![Screenshot_20190903_160114](https://user-images.githubusercontent.com/329963/64179898-2be52600-ce64-11e9-9622-2967a6c45681.png)
OpenModelica:
![Screenshot_20190903_160142](https://user-images.githubusercontent.com/329963/64179910-31db0700-ce64-11e9-96aa-157828423a9c.png)

**Comment by maltelenz** [comment]
And for good measure, WL/Mathematica:

![image](https://user-images.githubusercontent.com/329963/64180643-6d2a0580-ce65-11e9-9999-e7e083197c42.png)

**Comment by tobolar** [comment]
OK, I think the tools render well the variants with contours. I will prepare PR with Joints4a icon.
