### ISSUE TITLE
Text size of icon variable

### ISSUE THREAD

**Issue by max-privato** [modelica/ModelicaStandardLibrary#3108]
Not the biggest problem in the world, but...
I found an inconsistency in Electrical.QuasiStationary.Basic models.

Namely, the inductance value of the inductor is much smaller than the other values in similar components (resistor, capacitor, conductor.) 

In the Inductor I read:
 Text(extent={{150,-50},{-150,-80}}, textString="L=%L"),

while in the Resistor, Capacitor, Conductor I read: 
 Text(extent={{150,-40},{-150,-80}}, textString="R=%R_ref"),
 Text(extent={{150,-40},{-150,-80}}, textString="C=%C"),
 Text(extent={{150,-40},{-148,-80}}, textString="G=%G_ref"),

So the fix is simple: just change -50 into -40 in the Inductor.
I suppose it is also wise to change -148 into -150 in the conductor

**Comment by beutlich** [comment]
> Not the biggest problem in the world, but...

Thanks for reporting anayway.
