### ISSUE TITLE
Unusual Constant Source Voltage icon in MSL 3.2.3

### ISSUE THREAD

**Issue by MartinOtter** [modelica/ModelicaStandardLibrary#3162]
In MSL up to version 3.2.2, the icon for a constant source voltage was at it is standard in the electrical community:
![image](https://user-images.githubusercontent.com/7248038/67157977-a72a6a80-f332-11e9-96bc-209e33339bd0.png)

In MSL 3.2.3 the icon was changed to the non-standard form:
![image](https://user-images.githubusercontent.com/7248038/67157983-c4f7cf80-f332-11e9-9186-85996aee9de3.png)

Can someone explain, why this change was made.

**Comment by beutlich** [comment]
See #2718.

**Comment by beutlich** [comment]
See #2186.

**Comment by christiankral** [comment]
Some simulators, e.g. LTSpice,

![image](https://user-images.githubusercontent.com/4184218/67272976-de795280-f4bd-11e9-8b94-2fcf9f6baab4.png)

only use the circular symbol, so on my opinion the change is OK.

**Comment by beutlich** [comment]
Closing after silent acceptance.
