### ISSUE TITLE
Undefined name in annotation in Mechanics.MultiBody.Visualizers.Torus 

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#3172]
In Modelica.Mechanics.MultiBody.Visualizers.Torus in the following annotation `multiColoredSurface` is used. The name is not defined in the model or in the class from which it extends.
https://github.com/modelica/ModelicaStandardLibrary/blob/6e6180f71adeaeb6257081f226034dff92963848/Modelica/Mechanics/MultiBody/Visualizers.mo#L868-L869

**Comment by eshmoylova** [comment]
The example model Modelica.Mechanics.MultiBody.Examples.Elementary.Surfaces fails in Dymola pedantic mode due to this unresolved name. Note that the example also uses VoluminousWheel component that has issue #3173 and should fail in the pedantic mode until that issue is fixed.

**Comment by HansOlsson** [comment]
This is similar to #2004 but for a different visualizer.
