### ISSUE TITLE
Negative radius in Mechanics.MultiBody.Visualizers.VoluminousWheel

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaStandardLibrary#3173]
The default value for `ri` parameter in Modelica.Mechanics.MultiBody.Visualizers.VoluminousWheel is negative:
https://github.com/modelica/ModelicaStandardLibrary/blob/6e6180f71adeaeb6257081f226034dff92963848/Modelica/Mechanics/MultiBody/Visualizers.mo#L969

Given the default values of other parameters, the value for `ri` is -0.05. Modelica.SIunits.Radius has `min = 0`. `ri` is supposed to be used as an inner radius for a torus component.

The example model Modelica.Mechanics.MultiBody.Examples.Elementary.Surfaces uses the wheel with the default parameters, so `ri` there is negative.

**Comment by beutlich** [comment]
@dzimmer @MartinOtter How is it supposed to work?

**Comment by tobolar** [comment]
Negative values for `ri` shall be enabled. It is just a virtual radius. Proposal: use `SI.Length` instead of `Radius`.

**Comment by beutlich** [comment]
OK. Can do.

**Comment by tobolar** [comment]
@beutlich PR is yet ready. :-)
