### ISSUE TITLE
Change parameters of battery models

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#3179]
As discussed with @AHaumer, from the currently implemented parameter records some parameters shall be removed in order to use only physical parameters in the physical models. This change allows the strict separation of physical parameters and auxiliary calculation records which may be available from data sheets of batteries. Such an approach is already used in:

- `Modelica.Electrical.Machines.Utilities.SynchronousMachineData`
- `Modelica.Electrical.Machines.Utilities.TransformerData`

Changes to be applied: 

### `Modelica.Electrical.Batteries.ParameterRecords.CellData`

- Remove `Isc` as parameter `Ri` this the relevant parameter of the physical model
- Instead an auxiliary parameter record shall be implemented which computes the resistance `Ri` from the maximum open circuit voltage `OCVmax` and the short circuit current `Isc`

### `Modelica.Electrical.Batteries.ParameterRecords.RCData`  

- Remove time constant `T` as the physical parameters are fully determined by `R` and `C`
- Instead an auxiliary parameter record shall be implemented which utilizes the resistance and the time constant and calculates the capacitance from these parameters

**Comment by AHaumer** [comment]
@christiankral 
Maybe we have to clarify this on the phone, I don't remember fully how we planned the auxiliary records.
