### ISSUE TITLE
Problems with conversions

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3181]
Trying to convert ModelicaTestConversion4 in current master gives problems in Blocks and Electrical:

ModelicaTestConversion4.Blocks.Issue813:
  Classes are converted to ObsoleteModelica4.Blocks.Interfaces.Adaptors but ObsoleteModelica4.Blocks seems to be missing.

ModelicaTestConversion4.Blocks.Issue2441 lacks connections to the inputs of the tables (or make it a partial model).

ModelicaTestConversion4.Electrical.Spice3.Issue940
There might be some missing functionality in Dymola for converting record-members, but:
- The conversion script just says: `convertMessage("...Mosfet", "No support of automatic conversion for internal classes.")` should we really test unsupported conversions?
- The perimeter-parameter has been moved to a different position, and some parameters removed. I don't see how we could support that for functions.

Apart from that it looks good.

**Comment by HansOlsson** [comment]
I realized that it was best to directly check the conversions in more detail and found:

- [ ] The conversion is to `ObsoleteModelica4.Blocks.Interfaces.Adaptors.X` but the classes are named `ObsoleteModelica4.Blocks.Interfaces.X`. I don't which name is best.
- [ ] There is a conversion to `Modelica.Magnetic.FundamentalWave.Interfaces.BaseClasses.Machine` but the new class is called `Modelica.Magnetic.FundamentalWave.BaseClasses.Machine` (I think).
- [ ] There is a conversion from `Modelica.Blocks.Types.Init.DoNotUse_InitialIntegratorState` - but that was part of InitPID; so just eliminate that conversion line.
- [ ] There is a conversion from: `Modelica.Magnetic.FundamentalWave.Interfaces.BaseInductionMachine` - but it was called PartialBasicInductionMachine
- [ ] There is a conversion for `Modelica.StateGraph.PartialStep` adding nIn=1 and nOut=1; but the class was (and is) named `Modelica.StateGraph.Interfaces.PartialStep`. (There are also some other classes correctly converted.)

**Comment by beutlich** [comment]
#3198 fixes all but the third case.

As for the third case, I explicitly tested that the mentioned conversion rule

```
convertClass("Modelica.Blocks.Types.Init.DoNotUse_InitialIntegratorState",
              "Modelica.Blocks.Types.Init.NoInit");
```

has to be present. See our previous conversation in https://github.com/modelica/ModelicaStandardLibrary/pull/2898#issuecomment-504945873.
