### ISSUE TITLE
Accessing parameters in other models

### ISSUE THREAD

**Issue by Ciobrelis** [modelica/ModelicaStandardLibrary#3199]
It is rather a general question and hopefully someone could help me. 

I have a parameter under section _protected_ that is needed for further calculations:
`parameter Integer Ns = integer(ceil(L / dx))`
It shouldn't be modified that's why I placed it there. 
However, I want to access this parameter while building my general model. Something like: 
`componentName.Ns`

But as it is under protected section it is not possible. I did a work around by simply adding another parameter in general section: 
`parameter Integer N=Ns`
However, this parameter appears in the GUI and can be modified, which I would like to avoid by all means. 

Is there any solution for this? I hope it is clear what I mean.

**Comment by dietmarw** [comment]
This issue tracker is for issues regarding the Modelica Standard Library and not for general support questions. For those you should post your question on https://stackoverflow.com/tags/modelica and people will help you.
