### ISSUE TITLE
Modelica.Electrical.Spice3.Internal.MOS2 lacks equations

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3210]
When checking #3190 I noticed that Modelica.Electrical.Spice3.Internal.MOS2, Modelica.Electrical.Spice3.Semiconductors.M_NMOS2, Modelica.Electrical.Spice3.Semiconductors.M_PMOS2 lacked 22 Real equations.

I believe the reason is that Modelica.Electrical.Spice3.Internal.Mos.mos2CalcNoBypassCodeRevised was changed to not return some internal variables (like qm); but those variables are still declared in MOS2 and thus lack equations.

As far as I can see it wasn't an issue in 3.2.3.

**Comment by beutlich** [comment]
Confirmed. This was overlooked when merging #3017.
