### ISSUE TITLE
Relocate UsersGuide.ParameterDefaults

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#3248]
`Modelica.UsersGuide.ParameterDefaults` (Parameter defaults) summarises the convention how to handle default parameters. IMO this shall be a part of `Modelica.UsersGuide.Conventions` or even of `Modelica.UsersGuide.Conventions.ModelicaCode` instead. I.e. the class shall be moved to either of the packages.

**Comment by beutlich** [comment]
Either is fine for me.
