### ISSUE TITLE
Request to add data label headers to CombiTable components

### ISSUE THREAD

**Issue by jdrechse1** [modelica/ModelicaStandardLibrary#3252]
It appears that there is no way to add data labels or units to the header of data entered directly into CombiTable component. Am I correct? If so, can this be fixed in future release?

**Comment by beutlich** [comment]
Thanks for your report. Some quick thoughts:

* I guess you mean the external text files of the combi tables. You can add any comments there, but this simply will be ignored during file reading. Combi tables also support MAT files and tables given by Modelica arrays, where there is no chance to add comments.
* The existing text file format was invented for Dymola.
* SimulationX supports tables with units in a proprietary format.
* The ScientificDataFormat (https://2014.international.conference.modelica.org/proceedings/html/submissions/ECP14096885_AndresDiehlSommer.pdf and #1516) also had unit improvements as implementation requirement.
* CombiTimeTable can scale the time column, i.e., there is no need to have time values given in seconds.
* #2763 might be somehow related.
