### ISSUE TITLE
Icon of Modelica.Electrical.Batteries.BatteryStacks.SuperCap

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#3261]
The `%C` text and the heatPort square of th SuperCap Icon overlap:

![image](https://user-images.githubusercontent.com/14896695/70569720-c909d600-1b9a-11ea-8e93-08c74fe131c9.png)

Note, none of the three battery examples utilizes the heatPort.

**Comment by christiankral** [comment]
Added parameter name in c8f4a89bd16730b3c55a87657bb02e16d8fc7ca6

![image](https://user-images.githubusercontent.com/4184218/70855493-da6d1e00-1ecb-11ea-9477-bd1343282482.png)

**Comment by christiankral** [comment]
@beutlich if you are OK with the change, you can close this ticket, as the changes are directly applied to #3243
