### ISSUE TITLE
The gh-pages branch cannot be checked out cleanly on Windows

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3278]
Merely **checking** out gh-pages on Windows leads to more than a dozen of "Changes not staged for commit". The reason is that there are multiple files that only differ by case, as can be seen by comparing:

https://doc.modelica.org/Modelica%203.2.3/Resources/helpWSM/Modelica/Modelica.Electrical.Spice3.Internal.BJT.html
https://doc.modelica.org/Modelica%203.2.3/Resources/helpWSM/Modelica/Modelica.Electrical.Spice3.Internal.Bjt.html

**Comment by dietmarw** [comment]
I guess this can help you here: https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10

**Comment by beutlich** [comment]
You need to install WSL for that, see https://stackoverflow.com/questions/50839623/fsutil-the-request-is-not-supported-after-setcasesensitiveinfo

**Comment by HansOlsson** [comment]
Well, a simpler work-around was to just ignore it and not stage all changes.
But I expect that it will confuse others as well.

**Comment by beutlich** [comment]
> 
> 
> I guess this can help you here: https://www.windowscentral.com/how-enable-ntfs-treat-folders-case-sensitive-windows-10

Seems to work once you have WSL installed on Win10.

![grafik](https://user-images.githubusercontent.com/14896695/71308710-18080480-2400-11ea-9eec-979514448dac.png)
