### ISSUE TITLE
Pythagoras block doesn't handle negative y2

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#3280]
With u1IsHypotenuse = true, Math.Blocks.Pythagoras doesn't properly handle the case where y2 goes negative. The code should use an if-expression (rather than an if-equation) wrapped in a noEvent to prevent evaluating the square root with a negative value. As it is, an event is created when y2 goes negative, but that doesn't prevent the problem.

**Comment by beutlich** [comment]
@JoeRiel Thanks for reporting. Can you please create a pull request.
