### ISSUE TITLE
 Modelica.Electrical.Analog.Examples.SimpleTriacCircuit flawed

### ISSUE THREAD

**Issue by JoeRiel** [modelica/ModelicaStandardLibrary#3283]
The test circuit, as is, fails in MapleSim. It also fails in Dymola if R1 is changed. The problem is pulseCurrent, used to trigger the gate. When the sine wave load is negative, the trigger current must flow through the load, which is inductive. Pushing a pulse current, with a rise-time of 0, through an inductive load is a non-physical action. 
The simplest fix I could come up with is to replace the pulse current source with a signal current source driven by a pulse driver run through a 1-pole filter to achieve non-zero edges.  
Actually, a simpler fix would be just put a small (say 10nF) cap across the triac; that would provide a return path for the gate current but not otherwise affect the operation.

**Comment by christiankral** [comment]
Alternatively we could replace the `PulseCurrent` by the `TrapezoidCurrent` source.

**Comment by AHaumer** [comment]
@JoeRiel please check whether PR #3284 works
