### ISSUE TITLE
Not used images

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#3339]
There are image files in the following directories not used elsewhere.
- Modelica\Resources\Images\Fluid\Components
- Modelica\Resources\Images\Fluid\Dissipation\heatTransfer
- Modelica\Resources\Images\Fluid\Dissipation\pressureLoss

Note: Some of the images are used for Fluid icons. See also https://github.com/modelica/ModelicaStandardLibrary/pull/3322#issuecomment-575591955

**Comment by casella** [comment]
I'm sorry but I really have no time to worry about this. Anything you did is fine for me

**Comment by dietmarw** [comment]
@casella Could you please in your role as library officer take the time to come to a decision as to what to do with those. It is not critical for the MSL 4.0.0 release but simply saying it's somebody else's problem is not a solution :frowning: 
At least come up with a plan on when and how to deal with this.

**Comment by casella** [comment]
> @casella Could you please in your role as library officer take the time to come to a decision as to what to do with those.

IMHO this issue has a very, very low priority. I do not have time now to fully understand what the situation is, in order to take an informed decision on any action. I prefer to spend my limited time on more important issues, e.g. what to do with homotopy or how to fix models that produce non-physical results.

Hence, my decision is: defer this issue until the next release, unless anybody wants to pick this up (e.g. @tobolar), in which case I'm happy to completely delegate it.

**Comment by wischhusen** [comment]
I will have a look. Please give me this week for checking.

**Comment by wischhusen** [comment]
@beutlich I think I removed everything obsolete.

**Comment by dietmarw** [comment]
@wischhusen Where did you do that? You should send a PR so we can merge the changes.

**Comment by wischhusen** [comment]
in my fork

**Comment by dietmarw** [comment]
Could you please create a PR and reference this ticket (e.g., "ref: #3339") in the comment. Thanks.

**Comment by wischhusen** [comment]
no i can't.

**Comment by dietmarw** [comment]
Why not? What is the problem?

**Comment by wischhusen** [comment]
![Clipboard01](https://user-images.githubusercontent.com/3704662/74663542-3f7b1380-519c-11ea-9e96-cc9ba8b98542.png)

**Comment by dietmarw** [comment]
Try this link: https://github.com/wischhusen/Modelica-1/pull/new/master

**Comment by dietmarw** [comment]
A cleaned up PR is available here: #3429

**Comment by beutlich** [comment]
@dietmarw Can this be closed after merging #3429?

**Comment by dietmarw** [comment]
Fixed by #3429
