### ISSUE TITLE
Integrate HeatTransfer components from Dissipation library

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#343]
**Reported by kproelss on 28 Mar 2010 19:25 UTC**
Heat transfer coefficient correlations from the `Dissipation`library are going to be part of the MSL 3.2 under `Modelica.Fluid.Dissipation`. As decided at the 66th Design Meeting the existing corresponding component models are not included in that release, because their user interface has not been clearly defined yet.

Currently, variable modifications are required when using the component in addition to a heat port that needs to be connected. As a task for the next major release, the integration of such components into existing Fluid component models or their usage as top level system components needs to be discussed and a corresponding interface needs to be defined.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/343

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 21 May 2010 11:10 UTC**
Milestone MSL3.3 deleted

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Modified by fcasella on 14 Dec 2015 22:41 UTC**

**Comment by modelica-trac-importer** [comment]
**Changelog removed by fcasella on 14 Dec 2015 22:41 UTC**

**Comment by beutlich** [comment]
@wischhusen @casella Almost 9 years later, is this still desirable for MSL 4.0.0?

**Comment by wischhusen** [comment]
Honestly, the integration concept of the Heat´Transfer components (not functions) seems to be too complicated for regular users. So I would not insist to keep this issue open.

**Comment by beutlich** [comment]
> So I would not insist to keep this issue open.

Closing then.
