### ISSUE TITLE
NoiseExamples package has odd name

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#3440]
The package `Modelica.Blocks.Examples.NoiseExamples` contains examples using the `Modelica.Blocks.Noise` components.

Since it is already placed inside the `Examples` package, would it make more sense to call it `Modelica.Blocks.Examples.Noise`? The extra `Examples` seems redundant. I could not find similar examples elsewhere either.

**Comment by dietmarw** [comment]
There are still some documentation links that were not updated. PR is following.
