### ISSUE TITLE
Check of conversions

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3455]
Continuing 
https://github.com/modelica/ModelicaStandardLibrary/issues/3181#issuecomment-549259166

Old classes missing (note, I had https://github.com/modelica/ModelicaStandardLibrary/pull/3453 checked out, but I don't think that matters):
- [x] Modelica.Magnetic.FundamentalWave.BaseClasses.Machine
- [x] Modelica.Magnetic.FundamentalWave.BasicMachines.InductionMachines.{IM_SlipRing,IM_SquirrelCage}
- [x] Modelica.Magnetic.FundamentalWave.BasicMachines.SynchronousMachines.{SM_ElectricalExcited,SM_PermanentMagnet,SM_ReluctanceRotor}
- [x] Modelica_Synchronous.RealSignals.TimeBasedSources.Sin (for conversion of f->freqHz) (should be Sine) See #3456 for fix.

I also tried to check that all public elements in MSL are converted.

That seems to be the case for classes in MSL (excluding Examples, UserGuide, and partial ones).

For components conversions are missing for some "internal" variables, e.g., vbc in PNP due to https://github.com/modelica/ModelicaStandardLibrary/pull/3178
but for parameters and graphical ones only the following seems to lack conversions:
- [x] Modelica.Electrical.Machines.Utilities.SwitchYD idealCommutingSwitch
- [x] Modelica.Electrical.Spice3.Internal.MOS2 vp
- [x] Modelica.Magnetic.QuasiStatic.FundamentalWave.Utilities.SwitchYD idealCommutingSwitch
- [x] Modelica.Mechanics.MultiBody.Parts.Body z_a_start
- [x] Modelica.Fluid.Machines.BaseClasses.PartialPump show_NPSHa
I'm not sure if any of them are relevant.

(The above is excluding classes that are partially converted.)

**Comment by HansOlsson** [comment]
**Including** the partially converted ones we find some more classes that are gone without conversions (as far as I see).
- Modelica.Electrical.QuasiStationary.SinglePhase.Interfaces.RelativeSensor
- Modelica.Electrical.QuasiStationary.MultiPhase.Blocks.SingleToMultiPhase
- Modelica.Electrical.QuasiStationary.MultiPhase.Interfaces.RelativeSensor

Except for the previously reported parameter there seemed to be no issues for component.

**Comment by beutlich** [comment]
>     * Modelica.Magnetic.FundamentalWave.BaseClasses.Machine

Hm, I don't understand. There is

https://github.com/modelica/ModelicaStandardLibrary/blob/e40361763bdf818b9d6bbeaf8bf1f28212b3c80c/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L224-L225

where Modelica.Magnetic.FundamentalWave.Interfaces.PartialBasicInductionMachine is available in MSL 3.2.3 and Modelica.Magnetic.FundamentalWave.BaseClasses.Machine is available in MSL 4.0.0 Beta.1.

**Comment by beutlich** [comment]
> * Modelica.Electrical.Spice3.Internal.MOS2 vp
> * Modelica.Mechanics.MultiBody.Parts.Body z_a_start
> * Modelica.Fluid.Machines.BaseClasses.PartialPump show_NPSHa

These removals are already documented as non-backward compatible changes in the edited release notes (Modelica.UsersGuide.ReleaseNotes.Version_4_0_0).

**Comment by beutlich** [comment]
> * Modelica.Magnetic.FundamentalWave.BasicMachines.InductionsMachines.{Im_SlipRing,IM_SquirrelCage}

Covered by https://github.com/modelica/ModelicaStandardLibrary/blob/e40361763bdf818b9d6bbeaf8bf1f28212b3c80c/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L164-L167

> * Modelica.Magnetic.FundamentalWave.BasicMachines.SynchronousMachines.{SM_ElectricalExcited,SM_PermanentMagnet,SM_ReluctanceRotor}

Covered by https://github.com/modelica/ModelicaStandardLibrary/blob/e40361763bdf818b9d6bbeaf8bf1f28212b3c80c/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L168-L169

**Comment by christiankral** [comment]
> > * Modelica.Magnetic.FundamentalWave.BaseClasses.Machine
> 
> Hm, I don't understand. There is
> 
> https://github.com/modelica/ModelicaStandardLibrary/blob/e40361763bdf818b9d6bbeaf8bf1f28212b3c80c/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L224-L225
> 
> where Modelica.Magnetic.FundamentalWave.Interfaces.PartialBasicInductionMachine is available in MSL 3.2.3 and Modelica.Magnetic.FundamentalWave.BaseClasses.Machine is available in MSL 4.0.0 Beta.1.

@beutlich May I ask what part you do not understand here? I checked the conversion based on `ModelicaTestConversion4.Magnetic.FundamentalWave.Issue496.PartialBasicInductionMachine` and it works without issues.

**Comment by beutlich** [comment]
I do not understand what shall be fixed here. Or in other words: I do not understand, why @HansOlsson reported it as a potential conversion issue.

**Comment by christiankral** [comment]
OK then. I came to the same conclusion as @beutlich 

- [x] Modelica.Magnetic.FundamentalWave.BaseClasses.Machine
- [x] Modelica.Magnetic.FundamentalWave.BasicMachines.InductionMachines.{IM_SlipRing,IM_SquirrelCage}
- [x] Modelica.Magnetic.FundamentalWave.BasicMachines.SynchronousMachines.{SM_ElectricalExcited,SM_PermanentMagnet,SM_ReluctanceRotor}

convert all good and correctly.

**Comment by christiankral** [comment]
> **Including** the partially converted ones we find some more classes that are gone without conversions (as far as I see).
> 
>     * Modelica.Electrical.QuasiStationary.SinglePhase.Interfaces.RelativeSensor
> 
>     * Modelica.Electrical.QuasiStationary.MultiPhase.Blocks.SingleToMultiPhase
> 
>     * Modelica.Electrical.QuasiStationary.MultiPhase.Interfaces.RelativeSensor
> 
> 
> Except for the previously reported parameter there seemed to be no issues for component.

These issue shall be covered by 9d3a389edd5c55a52946df40cd6d307706f0ae99 and d9ecb20f4b2d4032bb516971f1c44f7459d32cb6

**Comment by beutlich** [comment]
PR would be welcome.

**Comment by christiankral** [comment]
>     * [ ]  Modelica.Electrical.Machines.Utilities.SwitchYD idealCommutingSwitch
> 
>     * [ ]  Modelica.Magnetic.QuasiStatic.FundamentalWave.Utilities.SwitchYD idealCommutingSwitch

These two issues is taken care of in 3fc099c829db57dc0fcf9d3459dd330ccaba1204 and #3467, respectively

**Comment by HansOlsson** [comment]
> > * Modelica.Magnetic.FundamentalWave.BaseClasses.Machine
> 
> Hm, I don't understand. There is
> 
> https://github.com/modelica/ModelicaStandardLibrary/blob/e40361763bdf818b9d6bbeaf8bf1f28212b3c80c/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L224-L225
> 
> where Modelica.Magnetic.FundamentalWave.Interfaces.PartialBasicInductionMachine is available in MSL 3.2.3 and Modelica.Magnetic.FundamentalWave.BaseClasses.Machine is available in MSL 4.0.0 Beta.1.

Hmm... 

I had to check more as well, and the issue is another line:
https://github.com/modelica/ModelicaStandardLibrary/blob/e40361763bdf818b9d6bbeaf8bf1f28212b3c80c/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L1821-L1821
that tries to convert something in `Modelica.Magnetic.FundamentalWave.BaseClasses.Machine`; but as noted that class was introduced in 4.0.0.

**Comment by HansOlsson** [comment]
> > * Modelica.Electrical.Spice3.Internal.MOS2 vp
> > * Modelica.Mechanics.MultiBody.Parts.Body z_a_start
> > * Modelica.Fluid.Machines.BaseClasses.PartialPump show_NPSHa
> 
> These removals are already documented as non-backward compatible changes in the edited release notes (Modelica.UsersGuide.ReleaseNotes.Version_4_0_0).

Ok, I guess I should have looked there first.
However, I noticed that this implies that something like convertMessage for components would be a good idea in the future.

**Comment by HansOlsson** [comment]
(In addition to #3492) I found the following additional issues:

- [ ] Modelica.Electrical.QuasiStationary.SinglePhase.Sensors.CurrentSensor had arg_i instead of arg_v as new connector name in conversion script.
 -[ ] Modelica.Media.Air.MoistAir.specificInternalEnergy_pTX had conversion for R->R_s
 -[ ] Modelica.Media.Air.ReferenceAir.Air_Utilities.Basic, Modelica.Media.Air.ReferenceMoistAir.Utilities.Ice09_Utilities.Basic, and Modelica.Media.Air.ReferenceMoistAir.Utilities.Water95_Utilities does not have R directly but in Constants
