### ISSUE TITLE
Update release notes of new/changed components/packages of MSL 4.0.0

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#3468]
This ticket is created to summarize missing release notes for MSL 4.0.0 based on https://groups.google.com/forum/#!msg/map-lib/Bcur73rRXlU/MUUd2CQ-BwAJ

**Comment by christiankral** [comment]
Refs #3467: SwitchYD

**Comment by beutlich** [comment]
@christiankral Is there anything left to do?
