### ISSUE TITLE
Improve doc strings and documentation of FluidHeatFlow

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaStandardLibrary#3474]
The doc strings and the HTML documentation of the FluidHeatFlow library shall be improved.

Examples:

- improve the wording of strings containing the term `over`, e.g. `Source2 over Ambient`
- Use more precise explanations, e.g., `Temperature increase of coolant in pipe with respect to temperature of inflow connector`

**Comment by TManikantan** [comment]
@christiankral Hi ,I recently assumed the role of Project Deputy, would you please take time to look at it? Do contact me for any help that I could provide with this ticket.

**Comment by TManikantan** [comment]
@christiankral @AHaumer  would you please look into this ticket
