### ISSUE TITLE
Missing conversion for "airGapS"?

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaStandardLibrary#3487]
I've to check once again:
In a model, I'm accessing `machine.airGapS.psi_ms` which should be converted to `machine.airGap.psi_ms` since the instance name has changed.

**Comment by dietmarw** [comment]
@AHaumer Could you give some more details? In which model are you accessing it. Looking for `airGapS` we have currently this conversion rule:

https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L1754-L1756

**Comment by AHaumer** [comment]
I've tried to isolate a test model out of my lib and tested once more: conversion correct. 
Sorry, closing ticket.
