### ISSUE TITLE
Conversion of SI fails.

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaStandardLibrary#3517]
The following testmodel currently fails the conversion (tested with Dymola 2020 and 2021 beta):
```mo
model TC
  import SI = Modelica.SIunits;
  parameter SI.Conversions.NonSIunits.Time_minute p1 = SI.Conversions.to_minute(42);
  parameter SI.Length p2 = 23;
  annotation(uses(Modelica(version="3.2.3")));
end TC;
```
The converted version looks like this:
```mo
model TC
  import      Modelica.Units.SI;
  parameter Modelica.Units.NonSI.Time_minute p1=SI.Conversions.to_minute(42);
  parameter Modelica.Units.SI.Length p2=23;
  annotation(uses(Modelica(version="4.0.0")));
end TC;
```
So the conversion of `p1` fails. 

It looks to me this is a tool issue, do you agree @HansOlsson ?

**Comment by HansOlsson** [comment]
Yes, and it is the same issue as in https://github.com/modelica/Modelica_LinearSystems2/pull/72

The tool-issue was specific to this combination of conversions and import-statements; and thus it hadn't been detected before.
