### ISSUE TITLE
Superfluous file in reference results

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#3521]
Is there a reason for the presence of this file, or is it just an accident?

https://github.com/modelica/MAP-LIB_ReferenceResults/blob/v4.0.0-beta.2%2B412d17023/ModelicaTest/Media/TestOnly/R134a_setState_pTX/MoistAir.csv

**Comment by beutlich** [comment]
Can you please create a PR to remove that (and other) CSV file(s). Thanks.

**Comment by maltelenz** [comment]
I guess I should push my pull request branch directly to the modelica/MAP-LIB_ReferenceResults repo, since it is a private repository?

**Comment by beutlich** [comment]
Ah, wrong repo. Let me see if I can transfer the issue.

**Comment by beutlich** [comment]
Done directly in browser: https://github.com/modelica/MAP-LIB_ReferenceResults/commit/5b013acbeef53b432faccbdac8d7dbabe5c104b4

**Comment by maltelenz** [comment]
For what it's worth, this was the only weird csv file I found.

**Comment by beutlich** [comment]
Probably some leftover when I tested locally. And CSV is not in gitignore for reasons 😄
