### ISSUE TITLE
Invalid connection line points in DirectCapacity

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#3539]
There are some connection lines with three elements in a point in `Modelica.Thermal.HeatTransfer.Examples.Utilities.DirectCapacity`. I assume it's a typo?

https://github.com/modelica/ModelicaStandardLibrary/blob/7b0253071a017fc08ad323676a27f3c1f2dc2bc0/Modelica/Thermal/HeatTransfer/Examples/Utilities/DirectCapacity.mo#L25-L30

**Comment by HansOlsson** [comment]
The line below the marked ones also have the same issue.

**Comment by beutlich** [comment]
@HansOlsson Could you please create a PR for it. Thank you.

**Comment by HansOlsson** [comment]
I'm looking into it. 

So far I found that it was introduced by:
https://github.com/modelica/ModelicaStandardLibrary/commit/07da25fe6ba7c30539e4ec4c60a8336e071bffad
so I now know what the intent was.

**Comment by beutlich** [comment]
Ah, now I get it.
