### ISSUE TITLE
Fix the mistakes in the help document of Modelica.Fluid

### ISSUE THREAD

**Issue by Satinelamp** [modelica/ModelicaStandardLibrary#3559]
In the `Modelica.Fluid.UsersGuide.ComponentDefinition.FluidConnectors`, there are two minor issues, 
1. In the example code, `FluidPort port_a, port_b;` should be `FluidPort port_a(redeclare each package Medium = Medium), port_b(redeclare each package Medium = Medium);`
![000000000000000000000000](https://user-images.githubusercontent.com/62006565/82703641-e5ac4d00-9ca6-11ea-9c0c-8f66468a1a61.png)

2. Missing dot in the code fragment `Medium density d_a, d_b`.
![00000000222222222222222](https://user-images.githubusercontent.com/62006565/82703648-e93fd400-9ca6-11ea-8110-e2192b492b33.png)

**Comment by beutlich** [comment]
Since only documentation is affected, we still can fix it with the final release of v4.0.0. Can you please create a pull request. Thanks.
