### ISSUE TITLE
Error message for out of bounds column in tables is broken

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#3562]
I think there might be an error around [here](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Resources/C-Sources/ModelicaStandardTables.c#L6288).

If I simulate this (incorrect) model in SystemModeler, I get this message, where the column number seems to print uninitialized memory:

```
model table_index_out_of_range
  Modelica.Blocks.Sources.Constant const(k = 1);
  Modelica.Blocks.Tables.CombiTable1Ds combiTable1Ds(columns = 3:5, table = {{0, 1, 2, 3}, {1, 1, 2, 3}, {2, 1, 2, 3}});
equation
  connect(const.y, combiTable1Ds.u);
end table_index_out_of_range;
```
I get this message (the long number is seemingly random):
```
[ERROR][GENERAL]: In external function .Modelica.Blocks.Types.ExternalCombiTable1D.constructor: ModelicaError: The column index -738195248 is out of range for table matrix "NoName(3,4)".
```

**Comment by beutlich** [comment]
tableID must not be accessed after it has been destroyed. The bug was introduced in 35162f86f1832374ae780bb07bcc5c4f80918c48 for #1899.
