### ISSUE TITLE
Unguarded clang pragmas in ModelicaStrings.c

### ISSUE THREAD

**Issue by d94pn** [modelica/ModelicaStandardLibrary#3564]
The guards for clang pragmas which is present in other C files:

```
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wtautological-compare"
#endif
```

```
#if defined(__clang__)
#pragma clang diagnostic pop
#endif
```

are omitted in ModelicaStrings.c, which yields compiler warnings for e.g. Visual Studio.

**Comment by beutlich** [comment]
Confirmed. I missed it when I pushed 98a20c066f913e84704489030a8a2c1909a01886.
