### ISSUE TITLE
More reference papers and examples about how to define the flow/volume model in Modelica.Fluid.

### ISSUE THREAD

**Issue by Satinelamp** [modelica/ModelicaStandardLibrary#3570]
I am learning how to build a thermo-fluid model with Modelica, I notice that in order to reduce the nonlinearity, it is recommended to use two different models: flow model and volume model, here is the explanation I found in a commercial library, but I am not sure how to arrange the equation in the components to realize this idea. So I suggest there should be some papers and examples about how to use this idea in the documentation.

![11111111111111111111111111](https://user-images.githubusercontent.com/62006565/83546585-7995d880-a533-11ea-92bb-5e483a2f0eff.jpg)

**Comment by hyumo** [comment]
This repo is mainly for Modelica Standard library development, I think your question is probably more appropriate for stackoverflow.

**Comment by thorade** [comment]
There already is a related question on SO:
https://stackoverflow.com/questions/62141433/how-to-define-the-flow-model-and-volume-model-in-modelica-components
