### ISSUE TITLE
Reference result missing for ModelicaTest FluxTubes FixedShape model in 3.2.3 build 4

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#3583]
There is no csv file for the model `ModelicaTest.FluxTubes.Shapes.FixedShape` here, even though there are comparison signals defined and the logs indicate the simulation succeeded:
https://github.com/modelica/MAP-LIB_ReferenceResults/tree/v3.2.3%2Bbuild.4/ModelicaTest/FluxTubes/Shapes/FixedShape

**Comment by beutlich** [comment]
Resolved by https://github.com/modelica/MAP-LIB_ReferenceResults/commit/4e8cf99d3384ca802bab80320ce7a5c0da2a2bd7. The comparisonSignals.txt contained a trailing blank which broke the process when extracting the trajectory variables.
