### ISSUE TITLE
Add more display unit for the SpecificEnergy and SpecificEnthalpy type

### ISSUE THREAD

**Issue by Satinelamp** [modelica/ModelicaStandardLibrary#3605]
There should be more display units for the SpecificEnergy and SpecificEnthalpy type, for example, "kJ/kg", "MJ/kg", cause in the thermo-fluid model, the steam enthalpy is often at the scale of "kJ/kg", it will be easier to understand the result with new display units.

![1111111111111111111](https://user-images.githubusercontent.com/62006565/86990871-37198880-c1d0-11ea-880c-c1da2daa5fad.jpg)

![22222222222222222](https://user-images.githubusercontent.com/62006565/86990898-4ac4ef00-c1d0-11ea-99ff-abb736b497f5.jpg)

**Comment by beutlich** [comment]
I believe this is a tool-issue and nothing that can be fixed in the library.

![image](https://user-images.githubusercontent.com/14896695/87001706-4f7da900-c1b8-11ea-8b19-63674de6ac24.png)

**Comment by Satinelamp** [comment]
Could you tell me what the dialogue window is in your screenshot?

**Comment by HansOlsson** [comment]
> Could you tell me what the dialogue window is in your screenshot?

That dialogue must be from a non-Dymola tool. 

You seem to be using Dymola and the procedure for adding display units in Dymola is described in the 1.3.17 Display units in 
Dymola 2021\Documentation\Dymola User Manual 1B.pdf

Please contact your normal support channel if you need more information.

**Comment by beutlich** [comment]
> Could you tell me what the dialogue window is in your screenshot?

That was from SimulationX. It has a large built-in database for (display) unit conversion, which however is not extensible by users.
