### ISSUE TITLE
Unused parameter in function

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaStandardLibrary#3622]
This parameter

https://github.com/modelica/ModelicaStandardLibrary/blob/39285d3bc28bc947613db51aff015f7ccd35b96f/Modelica/Electrical/Machines/SpacePhasors/Functions/ToSpacePhasor.mo#L14

shows up in function [toSpacePhasor](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/Electrical/Machines/SpacePhasors/Functions/ToSpacePhasor.mo), but is not used in the function body. 

@AHaumer, @christiankral, why was it defined in the first place?

**Comment by adrpo** [comment]
I think is just a copy paste mishap, if you look at:
https://github.com/modelica/ModelicaStandardLibrary/blob/39285d3bc28bc947613db51aff015f7ccd35b96f/Modelica/Electrical/Machines/SpacePhasors/Functions/FromSpacePhasor.mo#L13
there the parameter: `TransformationMatrix` is not used.

**Comment by adrpo** [comment]
See #3623

**Comment by christiankral** [comment]
The obsolete code fragments are leftovers from creating functions/inverse functions and blocks/inverse blocks from the same code base. So yes, the obsolete code shall be removed.

**Comment by christiankral** [comment]
See https://github.com/adrpo/Modelica/pull/1
