### ISSUE TITLE
Modelica.Utilities.Files.createDirectory fails if the directory does not exist

### ISSUE THREAD

**Issue by sjoelund** [modelica/ModelicaStandardLibrary#3660]
`Modelica.Utilities.Files.createDirectory` calls `fullPathName`, which fails if the path does not exist (on Linux). This means createDirectory does not work. Some possible solutions:

* Change `fullPathName` to never fail (revert to the old code with `getcwd`)
* Change `createDirectory` to not call `fullPathName` (but this would not fix older MSL versions)
* Add an argument to `fullPathName` to not fail (return the input perhaps), and create this additional file in the external sources

**Comment by beutlich** [comment]
Bug has been around for 7 years. If it is okay for you, I think we should revert 75d86f36e37c905db1c10f2d69b58324a11df1db (the realpath part) then.

**Comment by sjoelund** [comment]
I think it would be nicer to just see if the result is NULL and then use the old code. That shouldn't be very difficult to add. Otherwise the functionality is also very different in Linux and Windows since ../ would never be replaced
