### ISSUE TITLE
Search on doc.modelica.org not fully working

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3675]
The search was added in #3579 - but it doesn't seem to work reliably.

Typing "clutch" into the search field finds nothing for Dymola and MapleSim, sort of works for Wolfram System Modeler and fully for OpenModelica. Some other keywords finds thing, I don't know if it always works for OpenModelica or not.

I verified that https://doc.modelica.org/Modelica%204.0.0/Resources/helpDymola/Modelica_Mechanics_Rotational_Components.html#Modelica.Mechanics.Rotational.Components.Clutch and 
https://doc.modelica.org/Modelica%203.2.3/Resources/helpMapleSim/Mechanics/Rotational/Components/index.html#Clutch
do exist.

So it seems it is a misconfiguration in some way, or those help-pages do in some way not conform to algolia requirements.

**Comment by beutlich** [comment]
I also noticed and already reported it at https://github.com/algolia/docsearch-configs/issues/2753.

**Comment by beutlich** [comment]
However, "clutch" works for me, see

![grafik](https://user-images.githubusercontent.com/14896695/100370831-2e9ede80-3007-11eb-96e8-1ea13ddfe62d.png)

**Comment by HansOlsson** [comment]
Hmmm... It also works for me now, could be that it updated.

**Comment by beutlich** [comment]
@HansOlsson OK for you to close?

**Comment by HansOlsson** [comment]
> @HansOlsson OK for you to close?

Yes-
