### ISSUE TITLE
Combitable1d

### ISSUE THREAD

**Issue by deepak-mathur253** [modelica/ModelicaStandardLibrary#3678]
I was trying to import data using text format table using combitable1ds.

![image](https://user-images.githubusercontent.com/75309087/100731881-fb3ac600-33f1-11eb-8829-08b0f5b26480.png)

While checking if data imported is correct, I received below mentioned errors
![image](https://user-images.githubusercontent.com/75309087/100732116-510f6e00-33f2-11eb-97a7-e829bc4e182a.png)

Can anyone point out what I am doing wrong here.
Also, what is supposed to be mentioned in the blank field associated with table

**Comment by beutlich** [comment]
I am afraid we do not support table names with blanks. You should set a valid name (while I need to agree that we did neither specify nor dcoument what a valid name is).
