### ISSUE TITLE
Who can merge a PR

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#3717]
As the positions ot the project leader and project deputy of this MAP-LIB are vacant at the moment, I wonder who is in charge to merge the pull requests which passed all the checks.
IMO, anyone from MAP-LIB or package officers seem reasonable.

**Comment by AHaumer** [comment]
AFAIK every library officer, but you have to wait for the automatic tests and the approvals.

**Comment by beutlich** [comment]
In my ideal world, the assignee of the PR merges the changes. Every member of MAP-Lib can do so. Would be also ideal, if the open reviewers are unassigned.
