### ISSUE TITLE
PartialElementaryJoint should be extended from PartialTwoFrames

### ISSUE THREAD

**Issue by hyumo** [modelica/ModelicaStandardLibrary#3737]
`Modelica.Mechanics.MultiBody.Interfaces.PartialElementaryJoint` is inherently a child class of `Modelica.Mechanics.MultiBody.Interfaces.PartialTwoFrames` except for one extra line `Connections.branch(frame_a.R, frame_b.R);`

This would help make replaceable joints easier.

**Comment by tobolar** [comment]
This is a known issue in Mechanics, see e.g. https://github.com/modelica/ModelicaStandardLibrary/issues/2171#issuecomment-280661422 ("Overall the inheritance seems odd in the MultiBody-library, ...")
I prefer to solve this at once instead of having single problem-motivated solutions.

**Comment by tobolar** [comment]
See #3739
