### ISSUE TITLE
CombiTimeTable and similar not compiling

### ISSUE THREAD

**Issue by sede-fa** [modelica/ModelicaStandardLibrary#3757]
I have recently upgraded to MSL 4.0.0 from 3.2.3 and I have noticed that the models that contain combiTimeTable and similar models (i.e. ConbiTable1Ds etc.) also do not work. They fail to compile. 

I have tracked this back with the releases and found that it works with the 'MSL v4.0.0-beta.1 (2020-02-12)' release but stops working with 'MSL v4.0.0-beta.2 (2020-03-11)'. From the diff it looks like the ModelicaStnadardTables.h file was modified slightly as well as the Blocks/Tables.mo file to include the .h files. I didn't look thoroughly so maybe other files have a bigger influence on this.

I am using the latest release (6626538) and have tested this on Dymola 2019 FD01 with Visual studio 2017. I also tested the library on openmodelica 1.16 with MinGW and the same issue arose. Both computers on windows 10. I tested the models in modelica test (used many combiTable models) as well as the batteries examples, both give the same result.

As far as I can tell, all other models seem to be working fine, its just the models with combiTables that don't compile. I have attached my buildlog.txt file in case that helps (it's in German but can be put into google translate).

[buildlog.txt](https://github.com/modelica/ModelicaStandardLibrary/files/6023431/buildlog.txt)

**Comment by beutlich** [comment]
Let's hope it is resolved meanwhile.
