### ISSUE TITLE
Modelica Standard Tables in the FMI set/get state context

### ISSUE THREAD

**Issue by agnesramle** [modelica/ModelicaStandardLibrary#3759]
In the FMI 2.0 specification there is the concept of setting and getting FMU State. This doesn’t fit very well with Modelica Standard Tables since there are parts of the struct CombiTimeTable that are not allocated when calling the constructor (ModelicaStandardTables_CombiTimeTable_init) but in ModelicaStandardTables_CombiTimeTable_nextTimeEvent. To make sure that the constructor is called when setting FMU state on an FMU that is not yet initialized or has been reset is pretty straightforward to do. However, the compiler has no way to know that nextTimeEvent needs to be called in order to allocate memory nor if it needs to be called several times to reach the point where the state is saved. Are there any intentions to update this or are there thoughts/ideas on how to handle it?

**Comment by beutlich** [comment]
Isn't this a general issue with FMI and Modelica external objects, and as the Modelica Standard Tables happen to be the only external objects in MSL, it is only observed there? Hence I wonder if it is a duplicate issue of MO#1950 or really specific to the CombiTimeTable implementation.

**Comment by beutlich** [comment]
Closing since there was no more feedback from author.
