### ISSUE TITLE
Conversion from ModelicaServices and Complex version 3.2.3 to 4.0.0?

### ISSUE THREAD

**Issue by sjoelund** [modelica/ModelicaStandardLibrary#3768]
It seems as if 3.2.3 versions of ModelicaServices and Complex can be converted from all released versions except 3.2.3 - is this an error or is there some reason why they cannot be converted?

I can provide pull requests to maint/4.0.x and master if someone can tell me why this is.

**Comment by sjoelund** [comment]
I'll just assume it was simply forgotten and create a set of PRs.

**Comment by sjoelund** [comment]
#3770 #3771

**Comment by beutlich** [comment]
> 
> 
> #3770 #3771

All merged. Thanks.
