### ISSUE TITLE
getInstanceName and spatialDistribution not listed in ModelicaReference

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#3773]
ModelicaReference misses the getInstanceName function and spatialDistribution operator of MLS 3.3.

**Comment by dietmarw** [comment]
I was wondering when fixing this if using SVG directly would be allowed already for the next MSL release. This would allow me to include the equations displayed in https://specification.modelica.org/maint/3.5/operators-and-expressions.html#spatialdistribution

**Comment by dietmarw** [comment]
Sorry forgot to address this question proper ly to @HansOlsson and @MartinOtter

**Comment by HansOlsson** [comment]
> I was wondering when fixing this if using SVG directly would be allowed already for the next MSL release. This would allow me to include the equations displayed in https://specification.modelica.org/maint/3.5/operators-and-expressions.html#spatialdistribution

I don't know what Modelica Language version we will allow.
Note that Modelica 3.5 allows SVG for bitmaps, but we haven't clarified what is allowed for HTML (and the documentation will be in HTML).

**Comment by beutlich** [comment]
I'd also prefer to not include Modelica 3.5 elements as long as it is not clear what version next maint or main versions are based on.

**Comment by dietmarw** [comment]
OK that's fine. The other issue I have is how much ModelicaReference should be a copy of the Modelica Specification. The easiest solution would of course just to copy paste the parts from the specification. But this would also mean having to maintaining duplicates. Not sure how sensible this is.

**Comment by tobolar** [comment]
getInstanceName is, actually, a nice feature. If would be helpful to have some rule/reccomendation in MSL how to use it properly.

**Comment by dietmarw** [comment]
@tobolar  But ModelicaReference is not meant to be a guide line for MSL but rather a lookup for Modelica in general. If you wish some guideline for MSL then that should probably be added under `Modelica.UsersGuide.Conventions`.

**Comment by tobolar** [comment]
@dietmarw Definitely! Sorry for mixing it here.
