### ISSUE TITLE
Link rot

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaStandardLibrary#3776]
It seems like the following link is no longer valid:

https://github.com/modelica/ModelicaStandardLibrary/blob/19739745cf3ec63ac00763a355dd479e9d96254b/Modelica/Mechanics/MultiBody/Examples/Elementary/UserDefinedGravityField.mo#L55

https://earth-info.nga.mil/GandG/publications/tr8350.2/wgs84fin.pdf

**Comment by beutlich** [comment]
Neither the original link nor the updated link by #3777 are available.

@tobolar ftp://ftp.nga.mil/pub2/gandg/website/wgs84/NGA.STND.0036_1.0.0_WGS84.pdf might be another option.
