### ISSUE TITLE
What is the quality of the TankWithEmptyingPipe1 reference result?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaStandardLibrary#3782]
In the same spirit as #3778, I'm wondering about the quality of the reference result for `Modelica.Fluid.Examples.AST_BatchPlant.Test.TankWithEmptyingPipe1`.  This is what `tank1.medium.T` looks like in System Modeler:
<img width="400" alt="wsm-vs-reference" src="https://user-images.githubusercontent.com/25294143/111974391-a6859d00-8aff-11eb-85e6-c5da981a4b87.png">

The System Modeler result is quite robust to changes in method and tolerance parameters.

To build confidence for opening an issue about the difference, @maltelenz provided me with the corresponding OpenModelica result (which happens to be [treated as correct](https://libraries.openmodelica.org/branches/master/Modelica_4.0.0/Modelica_4.0.0.html) in their testing framework):
<img width="960" alt="om-reference-wsm" src="https://user-images.githubusercontent.com/25294143/111975201-9c17d300-8b00-11eb-833a-0d37b07aa897.png">

Although OpenModelica's result is closer to the reference, it is still sufficiently different to indicate a potential problem.

I'd be grateful if someone could confirm that the reference result is of good quality and worth trying to reproduce with good accuracy.

**Comment by HansOlsson** [comment]
From Dymola's perspective it's just a matter of varying the tolerance; with default tolerance we get close to reference and with stricter we get to about the same as the SystemModeler results.

**Comment by henrikt-ma** [comment]
OK, good to hear!

Despite the fact that System Modeler doesn't require stricter tolerance to produce this result, this is a typical example of a situation where I would have liked to see a routine that would involve setting a suitable `Tolerance` in the model, a reference being generated with even more strict tolerance, and a verification that the model's tolerance is sufficient to come close to the reference.

**Comment by beutlich** [comment]
Looks like we can fix it in the model. @HansOlsson Can you please create a PR setting a better tolerance. Thank you.

**Comment by beutlich** [comment]
> Can you please create a PR setting a better tolerance.

Available by #3813.
