### ISSUE TITLE
Invalid models ModelicaTest.Media.TestsWithFluids.MediaTestModels.*

### ISSUE THREAD

**Issue by rfranke** [modelica/ModelicaStandardLibrary#3852]
These models, for example `Modelica.Test.Media.TestsWithFluids.MediaTestModels.Air.SimpleAir`, solve at `volume.medium.p = 10,000 bar`, i.e. `1e9 Pa`. That's a lot.

`Modelica.Media.Interfaces.Types` defines:
```
type AbsolutePressure = SI.AbsolutePressure (
    min = 0,
    max = 1e8,
    ...
```
How could any tool present a valid solution at 1e9 Pa?

**Comment by henrikt-ma** [comment]
I think part of the answer is that models like this in the standard library means that tools can't have checking of min/max enabled by default, meaning that newly developed models don't get their trajectories checked against min/max either, unless the user takes active action to enable the checks.

To get out of this, we should make a sweep through all examples and make sure they pass with checks enabled.  Then, it will be a realistic option for tools to have the checks enabled by default.  Once there, it's unlikely that newly developed examples would come with min/max violations.
