### ISSUE TITLE
CO2 normalBoilingPoint = -1

### ISSUE THREAD

**Issue by jansilar** [modelica/ModelicaStandardLibrary#3860]
Hi, may be I miss something, but why is the CO2 normalBoilingPoint = -1 in Modelica.Media.IdealGases.Common.FluidData?
I think the correct value is 194.67°K (https://www.thermopedia.com/content/613/)
The Modelica.Media.Interfaces.Types.Temperature type has min=1, so that it is out of the range.

**Comment by HansOlsson** [comment]
I'll let one of the experts answer on exactly why that value is used; and what the implications are. But I can understand that it is more complicated as technically CO2 doesn't boil in the sense of going from liquid to gas at that point, but it sublimes from solid to gas; and the media-library is focused on liquids and gases.

**Comment by bilderbuchi** [comment]
..at normal pressure, that is. Between ~5 and ~70 bar, you can have a liquid-gas phase transition iirc.

**Comment by hubertus65** [comment]
It would be nice to have something like a symbolic constant for "Undefined" or "NaN" here, which doesn't exist in Modelica. The -1 was my workaround to that. Unless somebody has a much better idea, I propose to close it.

**Comment by bilderbuchi** [comment]
NaN really sounds useful, yeah. Inf, too, also with an eye on ieee754. See also https://github.com/modelica/ModelicaSpecification/issues/2048 https://github.com/modelica/fmi-standard/issues/644

**Comment by jansilar** [comment]
It seems -1 is currently the best solution. I am closing the task. Sorry for the two-year delay :(.
