### ISSUE TITLE
Does Modelica support any database?

### ISSUE THREAD

**Issue by Thamizh-selvan** [modelica/ModelicaStandardLibrary#3869]
I'm pretty new to modelica , I'm trying to setup and simulate a headlamp module with OpenModelica Connector. Trying to setup it as dynamic module. so It requires some datas for calculation, those were stored in SQL and Excel database. I tried to import datas from Excel using ExternData. But its not handy, Is there a way to import Data's from SQL using some queries or is there any other ways to import datas from Excel ? Thanks.

**Comment by dietmarw** [comment]
The issues here are for reporting problems. For general question you should rather ask here: https://stackoverflow.com/questions/tagged/modelica
