### ISSUE TITLE
Late inlining of Modelica.Mechanics.MultiBody.Frames.Internal.maxWithoutEvent

### ISSUE THREAD

**Issue by christoff-buerger** [modelica/ModelicaStandardLibrary#3908]
The current implementations of `maxWithoutEvent`, `maxWithoutEvent_d` and `maxWithoutEvent_dd` in `Modelica.Mechanics.MultiBody.Frames.Internal` all have the annotation `Inline=false`. This is not good. They should have `lateInline = true` annotated instead, to still enable inlining for performance optimization; after all, their implementations are just expressions.

@MartinOtter, @tobolar : Can you confirm this?

**Comment by MABackoffice** [comment]
Discussion during phone meeting with @MartinOtter and Modelon India:
Change should go to 4.1.0 (not 4.0.1), as it might change behavior.

**Comment by TManikantan** [comment]
@MartinOtter Hi would you please look at this issue, Please also let us know if we could help you?

**Comment by TManikantan** [comment]
> m this?

@MartinOtter do you agree with this solution

**Comment by TManikantan** [comment]
> The current implementations of `maxWithoutEvent`, `maxWithoutEvent_d` and `maxWithoutEvent_dd` in `Modelica.Mechanics.MultiBody.Frames.Internal` all have the annotation `Inline=false`. This is not good. They should have `lateInline = true` annotated instead, to still enable inlining for performance optimization; after all, their implementations are just expressions.
> 
> @MartinOtter, @tobolar : Can you confirm this?

@MartinOtter do you agree with this solution?

**Comment by MartinOtter** [comment]
Yes, good suggestion: Replace Inline=false by lateInline=true.
This should be backwards compatible.
