### ISSUE TITLE
Can I load Modelica of version 3.2.3. from the installed OpenModelica-v1.18.0-64bit?

### ISSUE THREAD

**Issue by Amuri44** [modelica/ModelicaStandardLibrary#3935]
I have installed OpenModelica-v1.18.0-64bit. I tried to load a package from my colleague, then the below warnings appeared.

```Modelica
[1] 13:06:29 Scripting Notification
Automatically loaded package Complex 4.0.0 due to uses annotation.

[2] 13:06:29 Scripting Notification
Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.

[3] 13:06:38 Syntax Warning
[C:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/RR/Transformation.mo: 15:26-15:814]: Lexer treating \ as \\, since \d is not a valid Modelica escape sequence.

[4] 13:06:38 Syntax Warning
[C:/Program Files/OpenModelica1.18.0-64bit/lib/omlibrary/RR/Transformation.mo: 15:26-15:893]: Lexer treating \ as \\, since \d is not a valid Modelica escape sequence.

[5] 13:06:38 Scripting Warning
RR requested package Modelica of version 3.2.3. Modelica 4.0.0 is used instead which states that it is only compatible with a conversion script. OpenModelica currently does not support conversion scripts and will proceed with potential issues as a result.
```

It seems that the package `RR` was built based on package Modelica of version 3.2.3, however, the  package Modelica that I have is of version 4.0.0. So, can I load Modelica of version 3.2.3. instead of Modelica 4.0.0 from my installed OpenModelica-v1.18.0-64bit?

**Comment by dietmarw** [comment]
This is not the place to file an issue with the tool you are using. You should rather contact the OpenModelica developers:
 - https://stackoverflow.com/questions/tagged/openmodelica
 - https://github.com/OpenModelica/OpenModelica/issues
