### ISSUE TITLE
ERROR: division leads to inf or nan at time X, (a=xx) / (b=yy), where divisor b is: firstOrder.T

### ISSUE THREAD

**Issue by Amuri44** [modelica/ModelicaStandardLibrary#3936]
I have a model designed in OpenModelica contains integrators and transfer functions and first orders. When I run this model in OMEdit, it works fine with some warnings:

```modelica
assert    | debug   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T
assert    | debug   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T
....
assert    | debug   | division leads to inf or nan at time 0.056, (a=7.2e+302) / (b=1e-15), where divisor b is: firstOrder.T
```
It seems that something related to block `firstOrder` is being fixed automatically by OMEdit but not when running FMI in julia, correct? the problem is not issued when (dt >=0.03 s) Any idea how to solve this issue?

**Comment by dietmarw** [comment]
This is not the place to file an issue with the tool you are using. You should rather contact the OpenModelica developers:
 - https://stackoverflow.com/questions/tagged/openmodelica
 - https://github.com/OpenModelica/OpenModelica/issues
