### ISSUE TITLE
ForceAndTorque model does not set color of force arrow

### ISSUE THREAD

**Issue by anotheruserofgithub** [modelica/ModelicaStandardLibrary#3989]
`Modelica.Mechanics.MultiBody.Forces.ForceAndTorque` does not forward the parameter `forceColor` to the `forceArrow` visualizer:
https://github.com/modelica/ModelicaStandardLibrary/blob/f4adb6f3a19db2460b69b82d4a676e8ef83a4b1b/Modelica/Mechanics/MultiBody/Forces/ForceAndTorque.mo#L50-L58

**Comment by beutlich** [comment]
It's closed once the corresponding PR is merged. Otherwise the release notes scripts finds this one while the PR might still be open.

**Comment by tobolar** [comment]
@anotheruserofgithub A good catch, no reason to apologize.
