### ISSUE TITLE
Modelica.Fluid.Examples.HeatingSystem won't simulate in OMEdit.

### ISSUE THREAD

**Issue by dfreethy** [modelica/ModelicaStandardLibrary#4014]
I am trying to simulate the Modelica.Fluid.Examples.HeatingSystem in OMEdit. However, I continue to get the following errors:

Warning: maximal number of iteration reached but no root found
Matrix singular!
Matrix singular!
under-determined linear system not solvable!
nonlinear system 499 fails: at t=0

proper start-values for some of the following iteration variables might help
Solving non-linear system 499 failed at time=0.
For more information please use -lv LOG_NLS.

Failed to solve the initialization problem with global homotopy with equidistant step size.
Simulation process failed. Exited with code 0xffffffffffffffff.
Unable to solve initialization problem.
Simulation terminated by an assertion at initialization
[HeatingSystem.zip](https://github.com/modelica/ModelicaStandardLibrary/files/9184630/HeatingSystem.zip)

I downloaded and am using the library from here.

**Comment by mestinso** [comment]
I think this is a tool issue and probably doesn't belong here specifically. Nonetheless, as far as I can tell there are still models that OpenModelica cannot run yet and this is one of them. Maybe the OpenModelica forums or OpenModelica github page are better places to raise the issue. Though I expect the OpenModelica developers are aware and I wouldn't be surprised if there is already an issue created related to this item.

It looks to me the error you are seeing is in alignment with the library coverage testing:
https://libraries.openmodelica.org/branches/v1.19/Modelica_4.0.0/files/Modelica_4.0.0_Modelica.Fluid.Examples.HeatingSystem.sim
Also see here: https://github.com/OpenModelica/OpenModelica/wiki/Library-Coverage-Testing
