### ISSUE TITLE
Duplicate non-identical component in Modelica.Electrical.QuasiStatic.Polyphase.Sources.FrequencySweepVoltageSource

### ISSUE THREAD

**Issue by filip-stenstrom** [modelica/ModelicaStandardLibrary#4021]
The component `m` is declared multiple times in `Modelica.Electrical.QuasiStatic.Polyphase.Sources.FrequencySweepVoltageSource`, but they are not identical.

Locally:
```
parameter Integer m=3 "Number of phases" annotation(Evaluate=true);
```

Inherited from `Modelica.Electrical.QuasiStatic.Polyphase.Interfaces.TwoPlug` which inherits it from `Modelica.Electrical.QuasiStatic.Polyphase.Interfaces.TwoPlugElementary`:
```
parameter Integer m(min=1) = 3 "Number of phases" annotation(Evaluate=true);
```

The specification requires that duplicate components are identical (MLS 3.4,, 5.6.1.4).

**Comment by AHaumer** [comment]
Thanks @filip-stenstrom for ponting this out.
The same issue can be found in `Modelica.Electrical.QuasiStatic.Polyphase.Sources.FrequencySweepCurrentSource`.
Both fixed with PR #4022
