### ISSUE TITLE
Is there any way to set the rolling wheels plane in x-z plane in Modelica.Mechanics.MulitiBody.Parts.RollingWheelSet ?

### ISSUE THREAD

**Issue by computational-physcis-2011301020083** [modelica/ModelicaStandardLibrary#4056]
Hi Guys.

I am trying to construct a complete modelica model of a loader,  and when constructing the boom arm and bucket, I set the direction of gravity in -y, but when I try to construct the rolling wheels, I find the direction of gravity is set to -z in example Modelica.Mechanics.MulitiBody.Elementary.RollingWheelSetPulling, that means the rolling plane is in x-y, and I find I can not change the setting, so Is there any way to set the rolling wheels plane in x-z plane in Modelica.Mechanics.MulitiBody.Parts.RollingWheelSet ?

Thanks

**Comment by computational-physcis-2011301020083** [comment]
Solved.

**Comment by tobolar** [comment]
> Solved.

How did you solve this?
