### ISSUE TITLE
Unit error in Modelica.Mechanics.MultiBody.Examples.Loops.Utilities.GasForce2

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaStandardLibrary#4080]
For `R_air`:
```
  constant SI.SpecificHeatCapacity R_air = Modelica.Constants.R / 0.0289651159;
```
we should introduce the molar mass of air, if I am not mistaken.

**Comment by tobolar** [comment]
Do you mean **SI units**?

Considering `dens = press/(R_air*T);`, the SI unit of `R_air` (J/(kg.K)) seems to be fine.

**Comment by tobolar** [comment]
Something like(?)
```
  constant SI.MolarMass MM_air = 0.0289651159;
  constant SI.SpecificHeatCapacity R_air = Modelica.Constants.R/MM_air;
```

**Comment by qlambert-pro** [comment]
That's what I had in mind. If we go by this proposal: https://github.com/modelica/ModelicaSpecification/pull/3266#discussion_r1019240597, this is the sort of things tools should start rejecting.
