### ISSUE TITLE
Unit error in Modelica.Electrical.Batteries.Examples.BatteryDischargeCharge

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaStandardLibrary#4098]
The bindings given to `cellData1.Ri` and `cellData2.Ri` do not pass unit checking.

They are both given an expression expressed in `"V"` when they are expecting one expressed in `"Ohm"`.

**Comment by qlambert-pro** [comment]
`Modelica.Electrical.Machines.Examples.DCMachines.DCPM_Drive` suffers from a similar issue:

`resistor.R` expects a value expressed in `"Ohm"` but is given one expressed in `"V"`

**Comment by beutlich** [comment]
Resolved by #4112.
