### ISSUE TITLE
[Translation Error] Quadrature Lobatto

### ISSUE THREAD

**Issue by Wendymely** [modelica/ModelicaStandardLibrary#4124]
Hello, 
Whenever I try to check or simulate the examples in the slPCMlib I get the following message:

```
[slPCMlib.Interfaces.basicPhTransModel: 53:3-57:40]: 
Type mismatch for positional argument 1 in Modelica.Math.Nonlinear.quadratureLobatto(f=slPCMlib.Examples.Case600FF_PCM_slPCMlib_SingleLayerPCM.lay.phTrModel.enthFcts.spHeatCap_baselineMelting). The argument has type:
  slPCMlib.Examples.Case600FF_PCM_slPCMlib_SingleLayerPCM.lay.phTrModel.enthFcts.spHeatCap_baselineMelting<function>(Real) => Real
expected type:
  f<function>(#Real) => #Real
```
I don’t quite understand this error message and I haven’t been able to find the solution to this. Has anyone had a similar issue and could maybe help me see what I’m overseeing? Thank you so much!

**Comment by henrikt-ma** [comment]
This is not the right type of question to ask in this repository.  Please direct it to your tool vendor, or maybe the slPCMlib library developers if it appears to be an issue with the library rather than your tool.  Closing.
