### ISSUE TITLE
Error with frame_resolve math in BasicAbsoluteAngularVelocity sensor

### ISSUE THREAD

**Issue by reedsullivan** [modelica/ModelicaStandardLibrary#4145]
https://github.com/modelica/ModelicaStandardLibrary/blob/a963d5bac1ac2b6c00ea1ca0567036a17f9f5262/Modelica/Mechanics/MultiBody/Sensors/Internal/BasicAbsoluteAngularVelocity.mo#L23

This function resolves the angular velocity of `frame_a.R` in the world frame, which is then resolved from `frame_a` to `frame_resolve`. That is not correct, as it resolves a world frame angular velocity from `frame_a` to `frame_resolve`.

There are two possible updates, with option 2 being preferred because I believe there are less operations involved.
1. `w = Frames.resolveRelative(Frames.angularVelocity2(frame_a.R), frame_a.R, frame_resolve.R);` where `Frames.angularVelocity1(frame_a.R)` is replaced by `Frames.angularVelocity2(frame_a.R)`.
2. `w = Frames.resolve2(frame_resolve.R, Frames.angularVelocity1(frame_a.R));` where the world frame angular velocity of `frame_a` is resolved in `frame_resolve` directly.

**Comment by tobolar** [comment]
It seems you are right, so I clasified this being a bug.

**Comment by reedsullivan** [comment]
Looks great! Thanks for the quick fix @tobolar.
