### ISSUE TITLE
Recompilation of binaries necessary

### ISSUE THREAD

**Issue by MatthiasBSchaefer** [modelica/ModelicaStandardLibrary#4178]
In the master branch e.g. commit ce36c07 examples which include a CombiTimeTable are not compiling, because the function
ModelicaStandardTables_CombiTimeTable_init3
can not be found in the binaries. The function was added to ModelicaStandardTables.c after the last built of the binaries. 
So a recompilation of the binaries for all platforms is necessary.

**Comment by beutlich** [comment]
I know, this is done (usually by me) just before a new release of the MSL is tagged.

**Comment by beutlich** [comment]
Duplicate of #3911.

**Comment by beutlich** [comment]
I am actually waiting for #4047 to get merged first. ⏳

**Comment by beutlich** [comment]
Meanwhile you can find the updated Windows binaries in https://github.com/beutlich/ModelicaStandardLibrary/tree/update-binaries.

**Comment by MatthiasBSchaefer** [comment]
Thank you !

**Comment by beutlich** [comment]
Resolved by #4250.
