### ISSUE TITLE
Dead link at modelica.org

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#4213]
The link here is dead:

https://github.com/modelica/ModelicaStandardLibrary/blob/d3ad60c312774a1bf84a74e830ccd55abcfb09d2/Complex.mo#L269

**Comment by HansOlsson** [comment]
I think we need to decide on https://github.com/modelica/www.modelica.org/issues/45 first
A benefit of keeping the existing license-part of the web-site is that existing links for generated documentation will remain useful.

**Comment by beutlich** [comment]
Duplicate of #4214.
