### ISSUE TITLE
Connect(p, p) in Modelica.Electrical.Analog.Examples.Utilities.SwitchedCapacitor?

### ISSUE THREAD

**Issue by TongYuan-MC** [modelica/ModelicaStandardLibrary#4245]
What is the purpose of connect(p, p)？Whether it is a valid connect-equation?
![image](https://github.com/modelica/ModelicaStandardLibrary/assets/153701357/340406c4-f41c-4141-b63f-da3fadfd1bf2)

**Comment by AHaumer** [comment]
I suppose that is a bug. 
If you release the mouse button during a connection too early, you get such a connection with zero length.
To me it seems that it doesn't affect the results, but we should remove it.

**Comment by HansOlsson** [comment]
> I suppose that is a bug. If you release the mouse button during a connection too early, you get such a connection with zero length. To me it seems that it doesn't affect the results, but we should remove it.

Agreed. Specifically it doesn't impact the result if there are other connection(s) to p, and two lines above we see another connection to p: `connect(IdealCommutingSwitch1.n1, p)`.
