### ISSUE TITLE
Unused ndim in MBS World

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaStandardLibrary#4246]
Does anybody knows what are the following protected parameters in `Modelica.Mechanics.MultiBody.World` for?
- ndim
- ndim2
- ndim_pointGravity

They are not used anywhere. Just being curious before deleting them.

@MartinOtter ?

**Comment by MartinOtter** [comment]
Can be deleted.
As I understand, there are now statements such as
   Shape x_arrowLine(...) if enableAnimation and animateWorld;
instead of 
  Shape x_arrowLine(...)[ndim]

When switching from 1/0 dimension arrays to conditional if-clauses, it was forgotten to remove the parameters
