### ISSUE TITLE
C code uses macros specified in internal/hidden ModelicaUtilities.h

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaStandardLibrary#4280]
The external C code in MSL uses macros. Example:

https://github.com/modelica/ModelicaStandardLibrary/blob/d0ff9bceb68621e4fc56f44a335e403947fd3c78/Modelica/Resources/C-Sources/ModelicaInternal.c#L150

These macros are defined in some `ModelicaUtilities.h` which has to be assumed is internal since it is in the `.CI` folder:

https://github.com/modelica/ModelicaStandardLibrary/blob/d0ff9bceb68621e4fc56f44a335e403947fd3c78/.CI/Test/ModelicaUtilities.h#L63-L127

However, as a tool vendor, I expect to provide my own `ModelicaUtilities.h`, which fulfills only the requirements given in the specification for such a file.

Should these macro definitions be moved out to a different `.h` in `Modelica/Resources/C-Sources`?

**Comment by beutlich** [comment]
Glad you reported this after #3871 got merged. Needs to be addressed before MSL v4.1.0 is released.
