### ISSUE TITLE
Unused and confusing parameters in Modelica.Mechanics.MultiBody.World

### ISSUE THREAD

**Issue by otronarp** [modelica/ModelicaStandardLibrary#4292]
The parameters `defaultN_to_m` and `defaultNm_to_m` in `World` are unused and doesn't have any impact on the visualization (since 4.0 the scaling of `Modelica.Mechanics.MultiBody.Visualizers.SignalArrow` is up to the tool). Shouldn't they be removed?

https://github.com/modelica/ModelicaStandardLibrary/blob/7ac7906706d000c1fc67a5812cd866618b63ffaf/Modelica/Mechanics/MultiBody/package.mo#L140-L145

**Comment by maltelenz** [comment]
#3934 :)

**Comment by HansOlsson** [comment]
> #3934 :)

I was just going to comment that:

> Preferably not!
> 
> Dymola does try to use them as default for the tool-specific settings for the specific model.

Similarly as in that one.

**Comment by otronarp** [comment]
I did feel a bit familiar :) Closing as duplicate of #3934.
