### ISSUE TITLE
MSL v4.1.0-beta.1 feedback: Incomplete experiment annotation for Modelica.Electrical.QuasiStatic.SinglePhase.Examples.MultipleResonance

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#4303]
Modelica.Electrical.QuasiStatic.SinglePhase.Examples.MultipleResonance should also get an experiment annotation like all other example models.

**Comment by AHaumer** [comment]
It has an experiment annotation but unfortunately only Interval, not Stop Time. I'll chhange that.

**Comment by casella** [comment]
Fixed by #4311.

@Harisankar-Allimangalath, @arunkumar-narasimhan, please back-port #4311 to the maintenance branch and close this ticket.

**Comment by Harisankar-Allimangalath** [comment]
@casella a PR for backporting this is created #PR4320 once that is closed , I shall close this issue . Thankyou

**Comment by beutlich** [comment]
Resolved in both master and maint/4.1.0.
