### ISSUE TITLE
MSL v4.1.0-beta.1 feedback: Inconsistent experiment annotations in Modelica.Electrical.PowerConverters.Examples.DCDC.ExampleTemplates

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#4309]
There are 3 example templates in Modelica.Electrical.PowerConverters.Examples.DCDC.ExampleTemplates, but only one of them (ChopperBuckBoost) has an experiment annoation.

https://github.com/modelica/ModelicaStandardLibrary/blob/da5c5de71f574b33a4f4631e09ba79682755f6d0/Modelica/Electrical/PowerConverters/Examples/DCDC/ExampleTemplates/ChopperBuckBoost.mo#L112-L115

I'd recommend to remove that experiment annotation on the partial models such that none of the three templates contains an experiment annotation.

**Comment by casella** [comment]
@Harisankar-Allimangalath @arunkumar-narasimhan, can you pleas port @AHaumer's commit to the maintenance branch and close this ticket. Thanks!

**Comment by beutlich** [comment]
Resolved in both master and maint/4.1.0.
