### ISSUE TITLE
Incorrect HTML of Testrun report breaks automation

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaStandardLibrary#4375]
I noticed that https://www.ltx.de/download/MA/Compare_MSL_v4.1.0/Testruns/Dymola/Modelica/testrun_report.html (and others) misses an opening tag for `<html>` before `<head>` which results in a failing shields.io XPath query. See #4212 for the context.

![grafik](https://github.com/modelica/ModelicaStandardLibrary/assets/14896695/a6db696a-3c33-476f-91e5-12ac52ca8718)

FYI @MatthiasBSchaefer

**Comment by MatthiasBSchaefer** [comment]
Thanks for the hint !
It is corrected now.

**Comment by beutlich** [comment]
Appears to be fixed by https://gitlab.com/LeoGall/ltx-resim/-/commit/2b572b45. Thx.
