### ISSUE TITLE
Modelica.Utilities.Files.exist does not work in Dymola

### ISSUE THREAD

**Issue by mdebaGH** [modelica/ModelicaStandardLibrary#4472]
Dear Modelica developers,

I have the necessity of checking if a file exists at runtime. I think that the best solution is using the function Modelica.Utilities.Files.exist(). To check its functionality I have developed a minimum working example which I report here below:

```mo
model checkExist

  Boolean Esiste(start = false);
equation

  if (time > 0.0) then
    Modelica.Utilities.Streams.print(String(time),"path/file.txt");
  end if;
  
  Esiste = Modelica.Utilities.Files.exist("path/file.txt");


end checkExist;
```

If I run this simple example in Open Modelica I get the right solution in which the variable "Esiste" becomes true at time = 0, as reported below.

![image](https://github.com/user-attachments/assets/aba58b6e-6a0e-4b97-a232-ae11b1dc4a10)

On the contrary if I run the very same example on dymola the variable "Esiste" does not change during the simulation, despite the file is correctly created. 

My setup is:

- Windows operative system
- MSL 4.0.0
- OpenModelica 1.23.0
- Dymola 2023x Refresh 1

Someone knows how to make the function Modelica.Utilities.Files.exist work in Dymola as well?

Thanks a lot.

Yours,

Marco

**Comment by casella** [comment]
@mdebaGH you should file a bug report with your Dymola representative. From a language point of view, I don't see any issue.

BTW, you did not specify if you always get "false" or "true" in Dymola. If you always get "false", mabye you have just specified a wrong path (e.g. in relative terms) so the file cannot be found. Try with an absolute path.

**Comment by mdebaGH** [comment]
Dear Francesco @casella,

Thanks for your reply. You are right, the information I have missed may be relevant indeed. The dymola output is always false, no matter what even if the file already exists. However the path is right (and already absolute). It is confirmed also by the fact that the file whose existance is checked is created, in the same specific path, by the modelica script itself.

I'll try to report the bug directly to dymola! Thanks again for your support!

Cheers,

Marco

**Comment by HansOlsson** [comment]
> @mdebaGH you should file a bug report with your Dymola representative. From a language point of view, I don't see any issue.

Actually there's a major flaw in the model:

1. Modelica.Utilities.Files.exist is (obviously) an impure function (it is even declared as such).
2. An impure function cannot be called at that place.

**Comment by casella** [comment]
I forgot about that, sorry, see Modelica Language Specification [Sect. 12.3](https://specification.modelica.org/maint/3.6/functions.html#pure-modelica-functions).

If I remember correctly, the rationale of that restriction is that if you put such a call in a continuous-time part of your model this could lead to weird results when you use non-trivial solvers, e.g. Runge-Kutta, which call the RHS of the differential equations back and forth in time during every step, or any variable step-size solver, that can try a long step and then reject it and try a lower one. Impure functions could cause unpredictable side effects during these calculations.

Indeed OpenModelica should reject your test case at compile-time, see OpenModelica/OpenModelica#13036. Maybe Dymola should also do the same.
