### ISSUE TITLE
Remove unneeded function bjtRenameParametersType

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#608]
**Modified by dietmarw on 13 Sep 2011 11:16 UTC**
In 33337aea75ee77ea9ada61a0dfaf4ef5db32bffc the function `bjtRenameParametersType` was removed. But since this removal  is a non-backward compatible change (user models might already use that function) the removal was reverted in 00580861925fd409b177a5cf5c3e564d0a76dd82. 

The function should be removed for the next non-backward compatible version of the MSL which also needs to supply a conversion script.

<sub>Keep this ticket as a reminder of that task.</sub>

----

**Reported by dietmarw on 13 Sep 2011 11:16 UTC**
In 33337aea75ee77ea9ada61a0dfaf4ef5db32bffc the function `bjtRenameParametersType` was removed. But since this removal  is a non-backward compatible change (user models might allready use that function) the removal was reverted in 00580861925fd409b177a5cf5c3e564d0a76dd82. 

The function should be removed for the next non-backward compatible version of the MSL which also needs to supply a conversion script.

<sub>Keep this ticket as a reminder of that task.</sub>

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/608

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 13 Sep 2011 11:16 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 13 Sep 2011 13:18 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by beutlich** [comment]
Also addressed by #3017.
