### ISSUE TITLE
Rename `SynchronousInductionMachines` to `SynchronousMachines`

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#733]
**Reported by dietmarw on 30 Apr 2012 13:25 UTC**
There seems to be a major flaw with the naming convention. To my knowledge an electrical machine can be either of induction type **or** of synchronous type but not both at the same time. Therefore calling a machine "Synchronous Induction Machine" doesn't make sense and the naming convention should be changed as soon as a conversion script allows this.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/733

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 30 Apr 2012 13:26 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by ahaumer on 1 May 2012 19:16 UTC**
Dear Dietmar,
this is a general naming issue, already discussed with Christian Kral; we tried to use:
"induction machine"                = German "Drehfeldmaschine"
"asynchronous (induction) machine" = German "Asynchronmaschine
"synchronous (induction) machine"  = German "Synchronmaschine"
"induction" means "voltage generation" German "Induktion" which holds for both machine types.
We're open to your suggestions ... (especially for an English term for German "Drehfeld" since "rotating (magnetic) field" sounds clumsy, but we have to observe backwards compatibility of naming until a conversion script is avaliable.
Regards, Toni

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 2 May 2012 06:49 UTC**
Toni, the problem is that in technical English inducton motor/machine is identical to asynchronous motors/machines. So in English if you use induction machine a person automatically assumes you are talking about an asynchronous machine and **not** about an synchronous one. Calling a machine Synchronous Induction Machine is simply confusing if not even plainly wrong. 

"Drehfeld" would translate as "Rotating magnetic field" (http://en.wikipedia.org/wiki/Rotating_magnetic_field) which is most likely a bit too cumbersome to use as a base class name I guess ;-).  Please not that also in that WP article they distinguish between synchronous and induction machines.

So renaming would make the structure of `Electrical.Machines` and `FundamentalWave` cleaner and more logical. Especially since you kind of applied the logic in the abbreviations you use. I.e., `AIM_...` and `SM_...` but not `SIM_...`. 

I know that the fix to this will have to wait for the next non-backward compatible version with conversion script. That's why I scheduled it for now for [[milestone:MSL4.0]].

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 10 Nov 2013 17:33 UTC**
Based on the discussion from comment 3 of #1348 how about a "induction"-less structure which also takes care of the new quasistatic components:

```
Modelica.Electrical.Machines.
  Transient
     AsynchronousMachines
     SynchronousMachines
     DCMachines
     Transformers
     Components
  QuasiStatic
     DCMachines
     (any future quasistatic sublibs)
```

Just an idea. 

A complete other approach would be rewriting the machine models in such a way that their behaviour, i.e., transient or quasistatic, can be made dependent on a parameter. So we would only have one DC  Machine model which can be made transient or quasistatic. But this should probably handled as a different enhancement in a separate ticket in case it is something you think is feasible.

**Comment by modelica-trac-importer** [comment]
**Changelog removed by dietmarw on 10 Nov 2013 17:33 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by AHaumer** [comment]
Yes we should do the rename to the common English term, but also "AsynchronousInductionMachines" to "InductonMachines" whenever a conversion script is applicable.

**Comment by dietmarw** [comment]
I would recommend to use 
`AsynchronousMachines` and `SynchronousMachines`  just like originally suggested. It simply reflects the physical nature best.

**Comment by AHaumer** [comment]
No English native speaker understands "Asynchronous Machine", the use the term "Induction Machine".

**Comment by dietmarw** [comment]
That's actually true. So `InductionMachine` it shall be then :-)

**Comment by dietmarw** [comment]
Just to make sure we are on the same page, for the MSL4.0.0 conversion the structure of the machines should be(as discussed earlier):
```
Modelica.Electrical.Machines.
  Transient
     InductionMachines
     SynchronousMachines
     DCMachines
     Transformers
     Components
  QuasiStatic
     DCMachines
     (any future quasistatic sublibs)
```

But it turns out in the meantime we now also got now `Modelica.Electrical.QuasiStatic`. So the structure should probably be 
```
Modelica.Electrical.
  Machines.
    InductionMachines
    SynchronousMachines
    DCMachines
    Transformers
    Components
  QuasiStatic.
    Machines.
      DCMachines
      (any future quasistatic sublibs)
```

Looks a bit strange tough. Any suggestions to make the structure cleaner and more systematic @christiankral @AHaumer?

**Comment by AHaumer** [comment]
There are no plans for other QuasiStatic Machines besides the exisiting DCMachines. 
QuasiStatic ACMachines are covered by Magnetic.QuasiStatic.FundamentalWave, that's sufficient.
