### ISSUE TITLE
Rename "IdealCommutingSwitch" to "IdealCommutatingSwitch"?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#778]
**Reported by leo&#46;gall on 17 Jul 2012 17:17 UTC**
The name of Modelica.Electrical.Analog.Ideal.IdealCommutingSwitch seems to use the wrong word:
"commute" (in German: pendeln/umwandeln)
instead of 
"commutate" (in German: kommutieren/umschalten).

Any native speakers here who could comment on this?

Renaming would have to wait for a conversion script, therefore I set milestone to MSL 4.0.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/778

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 18 Jul 2013 12:09 UTC**

**Comment by modelica-trac-importer** [comment]
**Changelog removed by otter on 18 Jul 2013 12:09 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by beutlich** [comment]
@ceraolo What is IEC's wording here?

**Comment by ceraolo** [comment]
there is not much on this in the IEV.

After some research there I would conclude that better than "Commuting switch" it is "SelectorSwitch: 
http://dom2.iec.ch/iev/iev.nsf/display?openform&ievref=151-12-24

 And better than "IntermediateSwitch" is "ReversingSwitch":
http://dom2.iec.ch/iev/iev.nsf/display?openform&ievref=151-12-25

**Comment by beutlich** [comment]
@AHaumer @christiankral @dietmarw Should we do the renming as propposed by @ceraolo?

- IdealCommutingSwitch -> IdealSelectorSwitch
- ControlledIdealCommutingSwitch -> ControlledIdealSelectorSwitch
- IdealIntermediateSwitch -> IdealReversingSwitch
- ControlledIdealIntermediateSwitch -> ControlledIdealReversingSwitch

**Comment by AHaumer** [comment]
To be honest: "Commuting" is wrong.
to commute = German "pendeln", ie. travel from home to work and back.
commutate = German "wenden, umpolen" - this is used in a DC machine,
I'd propose: Commuting -> TwoWay or ChangeOver (German "Wechselschalter")
Intermediate is correct (German "Kreuzschalter"), 
The alternative TwoWayDoublePoleRevesing is clumsy.

**Comment by beutlich** [comment]
> Any native speakers here who could comment on this?

@harmanpa Can you please help out on this language issue? Thanks.

**Comment by christiankral** [comment]
* SelectorSwitch seems to cover the type of switch we are taking about, but to me the affected model is a special selector switch whith just two switching positions. Selector switch sounds to me like having more than two switching positions. I am in favor of this proposal if some other native speakers agree to it. 
* ReversalSwitch seems the right term to me.

**Comment by AHaumer** [comment]
I have the same opinion as @christiankral regarding "Selector", but I don't understand "Reversal" = "umkehren"? I did look up in "Langenscheidt", finding the terms mentiones by my previous post.
I would keep "Intermediate" = "Kreuzschalter", but change "Commuting" to "TwoWay" = "Wechselschalter",

**Comment by harmanpa** [comment]
I'd favour the suggestion from @ahaumer of TwoWaySwitch, it is clear and easier to spell than Commutating!

**Comment by beutlich** [comment]
So it will be:

- IdealCommutingSwitch -> IdealTwoWaySwitch
- ControlledIdealCommutingSwitch -> ControlledTwoWaySwitch
- IdealIntermediateSwitch: keep as is
- ControlledIdealIntermediateSwitch: keep as is
