### ISSUE TITLE
Make Modelica.ComplexMath naming consistent

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaStandardLibrary#883]
**Reported by pharman on 21 Oct 2012 08:09 UTC**
The functions in Modelica.ComplexMath have a mixture of naming conventions, some match the built-in operators that they redefine for Complex, such as `sin(x)`, some add 's around the name, such as `'abs'(x)`.

According to https://github.com/modelica/ModelicaSpecification/issues/880 this is due to lookup from the enclosed Vectors package, however since direct-access to top-level packages with . was added there is no reason that built-in operators cannot be directly accessed such as `.abs(x)`.

It would therefore be beneficial to make the naming in ComplexMath more consistent and remove the 's.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/883

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by balodja** [comment]
Nice  suggestion. Any progress on that? :)

**Comment by beutlich** [comment]
It's addressed in #3047. So you might want to follow that pull request.
